#!/bin/bash
#
# This script compiles essential files needed before launching Ubuntu MATE Welcome
# for development.
#
# To prepare the software for use (e.g. packaging), pass "--build-only".
# To test the software, pass "--run-tests"
#
# Standard parameters can be passed.
#
params=$*

# Print help with "--help".
if [ "$1" == "--help" ]; then
    echo "Ubuntu MATE Welcome Development Script"
    echo "  <no parameters>         Start Welcome (dev version)"
    echo "                            + Compiles CSS"
    echo "  --build-only            Only build (for deployment)"
    echo "  --run-tests             Run tests (for CI and local)"
    echo "  --run-extended-tests    Run more rigorous tests (for package checks)"
    exit 0
fi

# Build CSS from LESS.
if [ "$(which lessc)" == "" ]; then
    echo "'lessc' not installed. Please install 'node-less'."
    exit 1
else
    echo -e "\033[94mCompiling CSS...\033[0m"
    dest=./data/css/welcome.css
    if [ -f "$dest" ]; then
        rm "$dest"
    fi

    # Compile each one and merge into one file
    touch "$dest"
    lessc ./sources/welcome.less "$dest"
    if [ $? == 0 ]; then
        echo -e "\033[92mFinished compiling CSS.\033[0m\n"
    else
        echo -e "\033[91mFailed to compile CSS.\033[0m\n"
        exit 1
    fi
fi

# Any special operations for development
if [ "$1" == "--build-only" ]; then
    ./scripts/build-locales.sh
    find . -name "__pycache__" -type d -exec rm -rf {} +
    exit 0

elif [ "$1" == "--run-tests" ]; then
    ./tests/run-tests.sh --quick
    exit 0

elif [ "$1" == "--run-extended-tests" ]; then
    ./tests/run-tests.sh --extended
    exit 0

else
    # Run Welcome
    cd `realpath $(dirname "$0")`
    ./ubuntu-mate-welcome -d $params
fi
