#! /usr/bin/python3
# -*- coding:utf-8 -*-
#
# Copyright 2012-2013 "Korora Project" <dev@kororaproject.org>
# Copyright 2013 "Manjaro Linux" <support@manjaro.org>
# Copyright 2014 Antergos
# Copyright 2015-2016 Martin Wimpress <code@flexion.org>
# Copyright 2015-2016 Luke Horwell <lukehorwell37+code@gmail.com>
#
# Ubuntu MATE Welcome is free software: you can redistribute it and/or modify
# it under the temms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ubuntu MATE Welcome is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ubuntu MATE Welcome. If not, see <http://www.gnu.org/licenses/>.
#

""" Welcome screen for Ubuntu MATE """

import gi
gi.require_version("Gdk", "3.0")
gi.require_version("Gtk", "3.0")
gi.require_version("Notify", "0.7")
gi.require_version("WebKit", "3.0")

import apt
import gettext
import inspect
import json
import logging
import os
import platform
import signal
import socket
import subprocess
import sys
import tempfile
import urllib.error
import urllib.parse
import urllib.request
import webbrowser
from aptdaemon.client import AptClient
from aptdaemon.gtk3widgets import AptErrorDialog, AptConfirmDialog, AptProgressDialog
import aptdaemon.errors
from aptdaemon.enums import *
from gi.repository import GLib, GObject, Gdk, Gtk, Notify, WebKit
from ctypes import cdll, byref, create_string_buffer
from threading import Thread
from getpass import getuser

# i18n
gettext.install("ubuntu-mate-welcome", "/usr/share/locale")

def set_proc_title(name=None):
    '''Set the process title'''

    if not name:
        name = os.path.basename(sys.argv[0])

    libc = cdll.LoadLibrary('libc.so.6')
    buff = create_string_buffer(len(name)+1)
    buff.value = name.encode("UTF-8")
    ret = libc.prctl(15, byref(buff), 0, 0, 0)

    if ret != 0:
        print("Failed to set process title")

    return ret

class SimpleApt(object):
    def __init__(self, packages, action):
        self._timeout=100
        self.packages = packages
        self.action = action
        self.source_to_update = None
        self.update_cache = False
        self.loop = GLib.MainLoop()
        self.client = AptClient()
        if self.packages:
            print('Processing: ' + ', '.join(self.packages))

    def on_error(self, error):
        if isinstance(error, aptdaemon.errors.NotAuthorizedError):
            # Silently ignore auth failures
            return
        elif not isinstance(error, aptdaemon.errors.TransactionFailed):
            # Catch internal errors of the client
            error = aptdaemon.errors.TransactionFailed(ERROR_UNKNOWN,str(error))
        error_dialog = AptErrorDialog(error)
        error_dialog.run()
        error_dialog.hide()

    def on_finished_fix_incomplete_install(self, transaction, status):
        self.loop.quit()
        if status == 'exit-success':
            Notify.init(_('Fixing incomplete install succeeded'))
            apt_notify=Notify.Notification.new(_('Successfully fixed an incomplete install.'), _('Fixing the incomplete install was successful.'), 'dialog-information')
            apt_notify.show()
            return True
        else:
            Notify.init(_('Fixing incomplete install failed'))
            apt_notify=Notify.Notification.new(_('Failed to fix incomplete install.'), _('Fixing the incomplete install failed.'), 'dialog-error')
            apt_notify.show()
            return False

    def on_finished_fix_broken_depends(self, transaction, status):
        self.loop.quit()
        if status == 'exit-success':
            Notify.init(_('Fixing broken dependencies succeeded'))
            apt_notify=Notify.Notification.new(_('Successfully fixed broken dependencies.'), _('Fixing the broken dependencies was successful.'), 'dialog-information')
            apt_notify.show()
            return True
        else:
            Notify.init(_('Fixing broken dependencies failed'))
            apt_notify=Notify.Notification.new(_('Failed to fix broken dependencies.'), _('Fixing the broken dependencies failed.'), 'dialog-error')
            apt_notify.show()
            return False

    def on_finished_update(self, transaction, status):
        # If the action is only to update do not display notifcations
        if self.action == 'update':
            self.loop.quit()
            if status == 'exit-success':
                return True
            else:
                return False
        elif self.action == 'install':
            if status != 'exit-success':
                self.do_notify(status)
                self.loop.quit()
                return False

            GLib.timeout_add(self._timeout,self.do_install)
            return True
        elif self.action == 'upgrade':
            if status != 'exit-success':
                self.do_notify(status)
                self.loop.quit()
                return False

            GLib.timeout_add(self._timeout,self.do_upgrade)
            return True

    def on_finished_install(self, transaction, status):
        self.loop.quit()
        if status != 'exit-success':
            return False
        else:
            self.do_notify(status)

    def on_finished_remove(self, transaction, status):
        self.loop.quit()
        if status != 'exit-success':
            return False
        else:
            self.do_notify(status)

    def on_finished_upgrade(self, transaction, status):
        self.loop.quit()
        if status != 'exit-success':
            return False
        else:
            self.do_notify(status)

    def do_notify(self, status):
        print('Status: ' + status)
        if self.action == 'install':
            title = _('Install')
            noun = _('Installation of ')
            action = _('installed.')
        elif self.action == 'remove':
            title = _('Remove')
            noun = _('Removal of ')
            action = _('removed.')
        elif self.action == 'upgrade':
            title = _('Upgrade')
            noun = _('Upgrade of ')
            action = _('upgraded.')

        # Do not show notifications when updating the cache
        if self.action != 'update':
            if status == 'exit-success':
                Notify.init(title + ' ' + _('complete'))
                apt_notify=Notify.Notification.new(title + ' ' + _('complete'), ', '.join(self.packages) + ' ' + _('has been successfully ') +action, 'dialog-information')
            elif status == 'exit-cancelled':
                Notify.init(title + ' ' + _('cancelled'))
                apt_notify=Notify.Notification.new(title + ' ' + _('cancelled'), noun + ', '.join(self.packages) + ' ' + _('was cancelled.'), 'dialog-information')
            else:
                Notify.init(title + ' ' + _('failed'))
                apt_notify=Notify.Notification.new(title + ' ' + _('failed'), noun + ', '.join(self.packages) + ' ' + _('failed.'), 'dialog-error')

            apt_notify.show()

    def do_fix_incomplete_install(self):
        # Corresponds to: dpkg --configure -a
        apt_fix_incomplete = self.client.fix_incomplete_install()
        apt_fix_incomplete.connect("finished",self.on_finished_fix_incomplete_install)

        fix_incomplete_dialog = AptProgressDialog(apt_fix_incomplete)
        fix_incomplete_dialog.run(close_on_finished=True, show_error=True,
                reply_handler=lambda: True,
                error_handler=self.on_error,
                )
        return False

    def do_fix_broken_depends(self):
        # Corresponds to: apt-get --fix-broken install
        apt_fix_broken = self.client.fix_broken_depends()
        apt_fix_broken.connect("finished",self.on_finished_fix_broken_depends)

        fix_broken_dialog = AptProgressDialog(apt_fix_broken)
        fix_broken_dialog.run(close_on_finished=True, show_error=True,
                reply_handler=lambda: True,
                error_handler=self.on_error,
                )
        return False

    def do_update(self):
        if self.source_to_update:
            apt_update = self.client.update_cache(self.source_to_update)
        else:
            apt_update = self.client.update_cache()
        apt_update.connect("finished",self.on_finished_update)

        update_dialog = AptProgressDialog(apt_update)
        update_dialog.run(close_on_finished=True, show_error=True,
                reply_handler=lambda: True,
                error_handler=self.on_error,
                )
        return False

    def do_install(self):
        apt_install = self.client.install_packages(self.packages)
        apt_install.connect("finished", self.on_finished_install)

        install_dialog = AptProgressDialog(apt_install)
        install_dialog.run(close_on_finished=True, show_error=True,
                        reply_handler=lambda: True,
                        error_handler=self.on_error,
                        )
        return False

    def do_remove(self):
        apt_remove = self.client.remove_packages(self.packages)
        apt_remove.connect("finished", self.on_finished_remove)

        remove_dialog = AptProgressDialog(apt_remove)
        remove_dialog.run(close_on_finished=True, show_error=True,
                        reply_handler=lambda: True,
                        error_handler=self.on_error,
                        )
        return False

    def do_upgrade(self):
        apt_upgrade = self.client.upgrade_system(True)
        apt_upgrade.connect("finished", self.on_finished_upgrade)

        upgrade_dialog = AptProgressDialog(apt_upgrade)
        upgrade_dialog.run(close_on_finished=True, show_error=True,
                        reply_handler=lambda: True,
                        error_handler=self.on_error,
                        )
        return False

    def install_packages(self):
        if self.update_cache:
            GLib.timeout_add(self._timeout,self.do_update)
        else:
            GLib.timeout_add(self._timeout,self.do_install)
        self.loop.run()

    def remove_packages(self):
        GLib.timeout_add(self._timeout,self.do_remove)
        self.loop.run()

    def upgrade_packages(self):
        if self.update_cache:
            GLib.timeout_add(self._timeout,self.do_update)
        else:
            GLib.timeout_add(self._timeout,self.do_upgrade)
        self.loop.run()

    def fix_incomplete_install(self):
        GLib.timeout_add(self._timeout,self.do_fix_incomplete_install)
        self.loop.run()

    def fix_broken_depends(self):
        GLib.timeout_add(self._timeout,self.do_fix_broken_depends)
        self.loop.run()

def update_repos():
    transaction = SimpleApt('', 'update')
    transaction.update_cache = True
    transaction.do_update()

def fix_incomplete_install():
    transaction = SimpleApt('', 'fix-incomplete-install')
    transaction.fix_incomplete_install()

def fix_broken_depends():
    transaction = SimpleApt('', 'fix-broken-depends')
    transaction.fix_broken_depends()

def process_packages(packages, action):
    if len(packages) and len(action):
        packages = packages.split(',')
    else:
        print('No package(s) supplied')
        return

    codename = platform.dist()[2]
    transaction = SimpleApt(packages, action)

    # Perform any pre-install configuration. Basically enabling repositories or
    # adding PPAs.
    if '0ad' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', '0ad', action])
        transaction.update_cache = True
        transaction.source_to_update = 'wfg-ubuntu-0ad-'+codename+'.list'
    elif 'appgrid' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'appgrid', action])
        transaction.update_cache = True
        transaction.source_to_update = 'appgrid-ubuntu-stable-'+codename+'.list'
    elif 'aptik' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'teejee2008', action])
        transaction.update_cache = True
        transaction.source_to_update = 'teejee2008-ubuntu-ppa-'+codename+'.list'
    elif 'audio-recorder' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'audio-recorder', action])
        transaction.update_cache = True
        transaction.source_to_update = 'audio-recorder-ubuntu-ppa-'+codename+'.list'
    elif 'boot-repair' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'boot-repair', action])
        transaction.update_cache = True
        transaction.source_to_update = 'yannubuntu-ubuntu-boot-repair-'+codename+'.list'
    elif 'btsync' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'btsync', action])
        transaction.update_cache = True
        transaction.source_to_update = 'btsync.list'
    elif 'emby-server' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'emby-server', action])
        transaction.update_cache = True
        transaction.source_to_update = 'emby-server.list'
    elif 'enpass' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'enpass', action])
        transaction.update_cache = True
        transaction.source_to_update = 'enpass.list'
    elif 'eviacam' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'eviacam', action])
        transaction.update_cache = True
        transaction.source_to_update = 'cesar-crea-si-ubuntu-eviacam-'+codename+'.list'
    elif 'flashplugin-installer' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'hal-flash', action])
        transaction.update_cache = True
    elif 'git' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'git-core', action])
        transaction.source_to_update = 'git-core-ubuntu-ppa-'+codename+'.list'
        transaction.update_cache = True
    elif 'gobby' in packages:
        if codename == 'trusty':
            subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'gobby', action])
            transaction.source_to_update = 'flexiondotorg-ubuntu-gobby-'+codename+'.list'
            transaction.update_cache = True
    elif 'google-chrome-stable' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'google-chrome', action])
        transaction.update_cache = True
        transaction.source_to_update = 'google-chrome.list'
    elif 'google-musicmanager-beta' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'google-musicmanager', action])
        transaction.update_cache = True
        transaction.source_to_update = 'google-musicmanager.list'
    elif 'google-talkplugin' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'google-talkplugin', action])
        transaction.update_cache = True
        transaction.source_to_update = 'google-talkplugin.list'
    elif 'nvidia-settings' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'graphics-drivers', action])
        transaction.update_cache = True
        transaction.source_to_update = 'graphics-drivers-ubuntu-ppa-'+codename+'.list'
    elif 'insync' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'insync', action])
        transaction.update_cache = True
        transaction.source_to_update = 'insync.list'
    elif 'libdvdcss2' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'libdvdcss2', action])
        transaction.update_cache = True
        transaction.source_to_update = 'libdvdcss2.list'
    elif 'libreoffice-core' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'libreoffice', action])
        transaction.update_cache = True
        transaction.source_to_update = 'libreoffice-ubuntu-ppa-'+codename+'.list'
    elif 'indicator-kdeconnect' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'vikoadi', action])
        transaction.update_cache = True
        transaction.source_to_update = 'vikoadi-ubuntu-ppa-'+codename+'.list'
    elif 'makemkv-bin' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'makemkv', action])
        transaction.update_cache = True
        transaction.source_to_update = 'heyarje-ubuntu-makemkv-beta-'+codename+'.list'
    elif ('minecraft-installer' in packages) or ('minecraft-server-installer' in packages):
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'minecraft', action])
        transaction.update_cache = True
        transaction.source_to_update = 'flexiondotorg-ubuntu-minecraft-'+codename+'.list'
    elif 'mumble' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'mumble', action])
        if codename == 'precise' or codename == 'trusty':
            transaction.update_cache = True
            transaction.source_to_update = 'mumble-ubuntu-release-'+codename+'.list'
    elif 'opera-stable' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'opera-stable', action])
        transaction.update_cache = True
        transaction.source_to_update = 'opera.list'
    elif 'owncloud-client' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'owncloud-client', action])
        transaction.update_cache = True
        transaction.source_to_update = 'owncloud-client.list'
    elif 'pithos' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'pithos', action])
        if codename == 'precise' or codename == 'trusty':
            transaction.update_cache = True
            transaction.source_to_update = 'pithos-ubuntu-ppa-'+codename+'.list'
    elif 'playonlinux' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'playonlinux', action])
        transaction.update_cache = True
    elif 'indicator-notifications-gtk2' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'recent-notifications', action])
        transaction.update_cache = True
        transaction.source_to_update = 'jconti-ubuntu-recent-notifications-'+codename+'.list'
    elif 'rednotebook' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'rednotebook', action])
        transaction.update_cache = True
        transaction.source_to_update = 'rednotebook-ubuntu-stable-'+codename+'.list'
    elif 'simplescreenrecorder' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'simplescreenrecorder', action])
        transaction.update_cache = True
        transaction.source_to_update = 'maarten-baert-ubuntu-simplescreenrecorder-'+codename+'.list'
    elif 'skype' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'skype', action])
        transaction.update_cache = True
    elif 'spideroakone' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'spideroakone', action])
        transaction.update_cache = True
        transaction.source_to_update = 'spideroakone.list'
    elif 'spotify-client' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'spotify', action])
        transaction.update_cache = True
        transaction.source_to_update = 'spotify.list'
    elif 'steam-launcher' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'steam', action])
        transaction.update_cache = True
        transaction.source_to_update = 'steam.list'
    elif 'stellarium' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'stellarium', action])
        transaction.update_cache = True
        transaction.source_to_update = 'stellarium-ubuntu-stellarium-releases-'+codename+'.list'
    elif 'synapse' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'synapse', action])
        transaction.update_cache = True
        transaction.source_to_update = 'synapse-core-ubuntu-testing-'+codename+'.list'
    elif 'syncthing' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'syncthing', action])
        transaction.update_cache = True
        transaction.source_to_update = 'syncthing.list'
    elif 'telegram' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'telegram', action])
        transaction.update_cache = True
        transaction.source_to_update = 'atareao-ubuntu-telegram-'+codename+'.list'
    elif 'terminator' in packages:
        if codename != 'xenial':
            subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'terminator', action])
            transaction.update_cache = True
            transaction.source_to_update = 'gnome-terminator-ubuntu-ppa-'+codename+'.list'
    elif 'tor-browser' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'tor-browser', action])
        transaction.update_cache = True
        transaction.source_to_update = 'webupd8team-ubuntu-tor-browser-'+codename+'.list'
    elif 'ubuntu-sdk' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'ubuntu-sdk', action])
        transaction.update_cache = True
        transaction.source_to_update = 'ubuntu-sdk-team-ubuntu-ppa-'+codename+'.list'
    elif 'uget' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'uget', action])
        transaction.update_cache = True
        transaction.source_to_update = 'plushuang-tw-ubuntu-uget-stable-'+codename+'.list'
    elif 'variety' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'peterlevi', action])
        transaction.update_cache = True
        transaction.source_to_update = 'peterlevi-ubuntu-ppa-'+codename+'.list'
    elif 'veracrypt' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'encryption', action])
        transaction.update_cache = True
        transaction.source_to_update = 'unit193-ubuntu-encryption-'+codename+'.list'
    elif 'virtualbox-5.0' in packages:
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'virtualbox-5.0', action])
        transaction.update_cache = True
        transaction.source_to_update = 'virtualbox.list'
    elif ('x2goclient' in packages) or ('x2goserver' in packages):
        subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer', 'x2go', action])
        transaction.update_cache = True
        transaction.source_to_update = 'x2go-ubuntu-stable-'+codename+'.list'

    if transaction.action == 'install':
        transaction.install_packages()
    elif transaction.action == 'remove':
        transaction.remove_packages()
    elif transaction.action == 'upgrade':
        transaction.upgrade_packages()
    else:
        print('The requested action is unknown')


class WelcomeConfig(object):
    """ Manages Welcome configuration """
    def __init__(self):
        # store our base architecture
        self.os_version = platform.dist()[1]
        self.os_codename = platform.dist()[2]
        self.os_title = 'Ubuntu MATE ' + self.os_version
        self._arch = os.uname()[4]

        # store we are a live CD session
        self._live = os.path.exists('/usr/share/glib-2.0/schemas/zubuntu-mate-live.gschema.override')

        # store full path to our binary
        self._welcome_bin_path = os.path.abspath(inspect.getfile(inspect.currentframe()))

        # directory for the configuration
        self._config_dir = os.path.expanduser('~/.config/ubuntu-mate/welcome/')

        # autostart directory
        self._autostart_dir = os.path.expanduser('~/.config/autostart/')

        # full path to the autostart symlink
        self._autostart_path = os.path.expanduser(os.path.join(self._autostart_dir, 'ubuntu-mate-welcome.desktop'))

        # ensure our config and autostart directories exists
        for _dir in [self._config_dir, self._autostart_dir]:
            if not os.path.exists(_dir):
                try:
                    os.makedirs(_dir)
                except OSError as err:
                    print(err)
                    pass

        # does autostart symlink exist
        self._autostart = os.path.exists(self._autostart_path)

    @property
    def arch(self):
        return self._arch

    @property
    def autostart(self):
        return self._autostart

    @autostart.setter
    def autostart(self, state):
        if state and not os.path.exists(self._autostart_path):
            # create the autostart symlink
            try:
                os.symlink('/usr/share/applications/ubuntu-mate-welcome.desktop', self._autostart_path)
            except OSError as err:
                print(err)
                pass
        elif not state and os.path.exists(self._autostart_path):
            # remove the autostart symlink
            try:
                os.unlink(self._autostart_path)
            except OSError as err:
                print(err)
                pass

        # determine autostart state based on absence of the disable file
        self._autostart = os.path.exists(self._autostart_path)

    @property
    def live(self):
        return self._live

class AppView(WebKit.WebView):
    def __init__(self):
        WebKit.WebView.__init__(self)

        self._config = WelcomeConfig()
        self._apt_cache = apt.Cache()
        self.connect('load-finished', self._load_finished_cb)
        self.connect('navigation-policy-decision-requested', self._nav_request_policy_decision_cb)
        self.l_uri = None

        # disable right-click context menu as it isn't needed.
        self.props.settings.props.enable_default_context_menu = False

    def _push_config(self):
        ### Global - On all pages ###
        self.execute_script("$('#os_title').html('%s')" % self._config.os_title)
        self.execute_script("$('#os_version').html('%s')" % self._config.os_version)
        self.execute_script("$('#autostart').toggleClass('fa-check-square', %s).toggleClass('fa-square', %s)" % (json.dumps(self._config.autostart), json.dumps(not self._config.autostart)))

        # If this is a Live session (booted from ISO) show the
        # 'Install OS' button, if running on an installed system show
        # the 'Install Software' button.
        if self._config.live:
            self.execute_script("$('#install').show();")
            self.execute_script("$('#software').hide();")
            self.execute_script("$('.live-session').hide();")
            self.execute_script("$('.live-session-only').show();")
        else:
            self.execute_script("$('#install').hide();")
            self.execute_script("$('#software').show();")
            self.execute_script("$('.live-session').show();")
            self.execute_script("$('.live-session-only').hide();")

        # Hide applications that are not supported on some architectures.
        # If neither a i686 or x86_64, we must be running on the Raspberry Pi (armv7) or the PowerPC.
        if self._config.arch == 'i686':
            self.execute_script("$('.i686-only').show();")
            self.execute_script("$('.x86_64-only').hide();")
            self.execute_script("$('.pc-only').show();")
            self.execute_script("$('.rpi-only').hide();")
        elif self._config.arch == 'x86_64':
            self.execute_script("$('.i686-only').hide();")
            self.execute_script("$('.x86_64-only').show();")
            self.execute_script("$('.pc-only').show();")
            self.execute_script("$('.rpi-only').hide();")
        else:
            # Not a PC, so could be PowerPC or ARM.
            self.execute_script("$('.i686-only').hide();")
            self.execute_script("$('.x86_64-only').hide();")
            self.execute_script("$('.pc-only').hide();")

            # If we find a Raspberry Pi 2 kernel, we're running on a Pi 2.
            if systemstate.session_type == 'pi':
                self.execute_script("$('.rpi-only').show();")
            else:
                self.execute_script("$('.rpi-only').hide();")

        # Display warnings if the user is not connected to the internet.
        if systemstate.is_online:
            self.execute_script("$('.offline').hide();")
            self.execute_script("$('.online').show();")
        else:
            self.execute_script("$('.offline').show();")
            self.execute_script("$('.online').hide();")

        ### Main Menu ###
        if self.current_page == 'index.html':
            if systemstate.session_type == 'guest':
                # Disable features that are unavailable to guests.
                self.execute_script("$('#gettingstarted').hide();")
                self.execute_script("$('#software').hide();")
                self.execute_script("$('#introduction').addClass('btn-success');")
                self.execute_script("$('#community').addClass('btn-success');")

        ### Splash ###
        if self.current_page == 'splash.html':
            # Determine which screen to show after the splash screen.
            if systemstate.session_type == 'live':
                self.execute_script('var splashNextPage = "hellolive"')
            elif systemstate.session_type == 'guest':
                self.execute_script('var splashNextPage = "helloguest"')
            else:
                self.execute_script('var splashNextPage = "index"')

        ### Chat Page ###
        if self.current_page == 'chatroom.html':
            if self._apt_cache['hexchat'].is_installed:
                self.execute_script("$('.hexchat').show();")
                self.execute_script("$('.webchat').hide();")
            else:
                self.execute_script("$('.hexchat').hide();")
                self.execute_script("$('.webchat').show();")

        ### Getting Started Page ###
        if self.current_page == 'gettingstarted.html':
            # Display information tailored to graphics vendor (Getting Started / Drivers)
            self.execute_script('var graphicsVendor = "' + systemstate.graphics_vendor + '";')
            self.execute_script('var graphicsGrep = "' + systemstate.graphics_grep + '";')
            self.execute_script('$("#boot-mode").html("' + systemstate.boot_mode + '")')

            # Display system information if successfully cached.
            if systemstate.system_info_cached:
                systemstate.append_system_info(self)

        ### Software Page ###
        if self.current_page == 'software.html' or self.current_page == 'gettingstarted.html':
            self.execute_script('var system_arch = "' + self._config.arch + '"' )

        # Change button states for Software.html
        # TODO - Read this from JSON (Dynamic Apps)
        for package in ['0ad', 'appgrid', 'aptik', 'asunder',
        'audacity', 'audio-recorder', 'bleachbit', 'blender',
        'boot-repair', 'btsync-gui', 'bzr-explorer', 'caja-dropbox',
        'caja-share', 'calibre', 'chromium-browser', 'chromium-bsu',
        'darktable', 'dia-gnome', 'dvdstyler', 'easytag',
        'emby-server', 'enpass', 'extremetuxracer', 'eviacam',
        'evolution', 'filezilla', 'firefox', 'flashplugin-installer',
        'flightgear', 'focuswriter', 'frozen-bubble', 'gcompris',
        'geany', 'gimp', 'git-cola', 'glade', 'glabels',
        'gnome-schedule', 'gnote', 'gnucash', 'gobby',
        'google-chrome-stable', 'google-earth-stable',
        'google-musicmanager-beta', 'google-talkplugin', 'gparted',
        'gramps', 'handbrake', 'hardinfo', 'hedgewars',
        'icedtea-7-plugin', 'indicator-kdeconnect',
        'indicator-notifications-gtk2', 'inkscape', 'insync',
        'libavcodec-extra', 'libdvdcss2', 'libreoffice-core',
        'libreoffice-base', 'libreoffice-draw', 'libreoffice-math',
        'liferea', 'makemkv-bin', 'meld', 'minecraft-installer',
        'minecraft-server-installer', 'mumble', 'mypaint',
        'mysql-workbench', 'neverball', 'neverputt', 'nexuiz',
        'opera-stable', 'ssh', 'owncloud-client', 'parcellite',
        'pavucontrol', 'pgadmin3', 'pithos', 'pitivi', 'planner',
        'playonlinux', 'poedit', 'pysolfc', 'rapid-photo-downloader',
        'rednotebook', 'redshift', 'remmina', 'retext', 'scribus',
        'simplescreenrecorder', 'skype', 'software-center',
        'spideroakone', 'spotify-client', 'steam-launcher',
        'stellarium', 'supertuxkart', 'sweethome3d', 'synapse',
        'synaptic', 'syncthing', 'teeworlds', 'telegram', 'terminator',
        'tor-browser', 'ubuntu-make', 'ubuntu-sdk', 'uget', 'variety',
        'veracrypt', 'virt-manager', 'virtualbox-5.0', 'warzone2100',
        'wesnoth', 'workrave', 'x2goclient', 'x2goserver', 'zim']:
            if package == 'virtualbox-5.0':
                # Dots (.) in CSS Classes are not allowed.
                css_class = 'virtualbox-5-0'
            else:
                css_class = package

            try:
                if self._apt_cache[package].is_installed:
                    self.execute_script("$('."+css_class+"-install').hide();")
                    self.execute_script("$('."+css_class+"-reinstall').show();")
                    self.execute_script("$('."+css_class+"-remove').show();")
                    self.execute_script("$('."+css_class+"-upgrade').show();")
                else:
                    self.execute_script("$('."+css_class+"-install').show();")
                    self.execute_script("$('."+css_class+"-reinstall').hide();")
                    self.execute_script("$('."+css_class+"-remove').hide();")
                    self.execute_script("$('."+css_class+"-upgrade').hide();")
            except:
                self.execute_script("$('."+css_class+"-install').show();")
                self.execute_script("$('."+css_class+"-reinstall').hide();")
                self.execute_script("$('."+css_class+"-remove').hide();")
                self.execute_script("$('."+css_class+"-upgrade').hide();")

    def _load_finished_cb(self, view, frame):
        self._push_config()

    def _nav_request_policy_decision_cb(self, view, frame, net_req, nav_act, pol_dec):
        uri = net_req.get_uri()
        self.current_page = uri.rsplit('/', 1)[1]

        try:
            if uri.index('#') > 0:
                uri = uri[:uri.index('#')]
        except ValueError:
            pass

        if uri == self.l_uri:
            pol_dec.use()
            return True

        if uri.startswith('cmd://'):
            self._do_command(uri)
            return True

        self.l_uri = uri

        page = urllib.request.urlopen(uri)
        frame.load_string(page.read().decode(), "text/html", "iso-8859-15", page.geturl())
        pol_dec.ignore()
        return True

    def _do_command(self, uri):
        if uri.startswith('cmd://'):
            uri = uri[6:]

        if uri.startswith('apt-install?'):
            process_packages(uri[12:], 'install')
            self._apt_cache.close()
            self._apt_cache = apt.Cache()
            self._push_config()
        elif uri.startswith('apt-remove?'):
            process_packages(uri[11:], 'remove')
            self._apt_cache.close()
            self._apt_cache = apt.Cache()
            self._push_config()
        elif uri.startswith('apt-upgrade?'):
            process_packages(uri[12:], 'upgrade')
            self._apt_cache.close()
            self._apt_cache = apt.Cache()
            self._push_config()
        elif uri == 'apt-update':
            update_repos()
            self._apt_cache.close()
            self._apt_cache = apt.Cache()
            self._push_config()
        elif uri == 'fix-incomplete-install':
            fix_incomplete_install()
            self._apt_cache.close()
            self._apt_cache = apt.Cache()
            self._push_config()
        elif uri == 'fix-broken-depends':
            fix_broken_depends()
            self._apt_cache.close()
            self._apt_cache = apt.Cache()
            self._push_config()
        elif uri == 'autostart':
            self._config.autostart ^= True
            self._push_config()
        elif uri == 'install':
            subprocess.Popen(['ubiquity','gtk_ui'])
        elif uri == 'backup':
            subprocess.Popen(['deja-dup-preferences'])
        elif uri == 'chatroom':
            subprocess.Popen(['hexchat','IRC://irc.freenode.net/ubuntu-mate'])
        elif uri == 'control':
            subprocess.Popen(['mate-control-center'])
        elif uri == 'drivers':
            subprocess.Popen(['software-properties-gtk','--open-tab=4'])
        elif uri == 'firewall':
            subprocess.Popen(['gufw'])
        elif uri == 'language':
            subprocess.Popen(['gnome-language-selector'])
        elif uri == 'users':
            subprocess.Popen(['users-admin'])
        elif uri == 'quit':
            Gtk.main_quit()
        elif uri == 'tweak':
            subprocess.Popen(['mate-tweak'])
        elif uri == 'update':
            subprocess.Popen(['update-manager'])
        elif uri == 'printers':
            subprocess.Popen(['system-config-printer'])
        elif uri == 'gparted':
            subprocess.Popen(['gparted-pkexec'])
        elif uri == 'sysmonitor':
            subprocess.Popen(['mate-system-monitor'])
        elif uri == 'hardinfo':
            subprocess.Popen(['hardinfo'])
        elif uri.startswith('run?'):
            subprocess.Popen([uri[4:]])
        elif uri.startswith('link?'):
            webbrowser.open_new_tab(uri[5:])
        elif uri == 'checkInternetConnection':
            systemstate.check_internet_connection()
            if systemstate.is_online:
                self.execute_script("$('.offline').hide();")
                self.execute_script("$('.online').show();")
            else:
                self.execute_script("$('.offline').show();")
                self.execute_script("$('.online').hide();")
        elif uri == 'get-spec-ram':
            systemstate.append_system_info(self, True)
        else:
            print('Unknown command: %s' % uri)

class WelcomeApp(object):
    def __init__(self):
        # establish our location
        self._location = os.path.dirname( os.path.abspath(inspect.getfile(inspect.currentframe())) )

        # check for relative path
        if( os.path.exists( os.path.join(self._location, 'data/' ) ) ):
            print('Using relative path for data source. Non-production testing.')
            self._data_path = os.path.join(self._location, 'data/')
        elif( os.path.exists('/usr/share/ubuntu-mate-welcome/') ):
            print('Using /usr/share/ubuntu-mate-welcome/ path.')
            self._data_path = '/usr/share/ubuntu-mate-welcome/'
        else:
            print('Unable to source the ubuntu-mate-welcome data directory.')
            sys.exit(1)

        self._build_app()

    def _build_app(self):

        # build window
        w = Gtk.Window()
        w.set_position(Gtk.WindowPosition.CENTER)
        w.set_wmclass('Ubuntu MATE Welcome', 'Ubuntu MATE Welcome')
        w.set_title('Welcome to Ubuntu MATE')

        # http://askubuntu.com/questions/153549/how-to-detect-a-computers-physical-screen-size-in-gtk
        s = Gdk.Screen.get_default()
        if s.get_height() <= 600:
            w.set_size_request(768, 528)
        else:
            w.set_size_request(800, 552)

        icon_dir = os.path.join(self._data_path, 'img', 'welcome', 'ubuntu-mate-icon.svg')
        w.set_icon_from_file(icon_dir)

        # build webkit container
        mv = AppView()

        # load our index file
        file = os.path.abspath(os.path.join(self._data_path, 'splash.html'))
        uri = 'file://' + urllib.request.pathname2url(file)
        mv.open(uri)

        # build scrolled window widget and add our appview container
        sw = Gtk.ScrolledWindow()
        sw.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)
        sw.add(mv)

        # build an autoexpanding box and add our scrolled window
        b = Gtk.VBox(homogeneous=False, spacing=0)
        b.pack_start(sw, expand=True, fill=True, padding=0)

        # add the box to the parent window and show
        w.add(b)
        w.connect('delete-event', self.close)
        w.show_all()

        self._window = w
        self._appView = mv

    def run(self):
        signal.signal(signal.SIGINT, signal.SIG_DFL)
        Gtk.main()

    def close(self, p1, p2):
        Gtk.main_quit(p1, p2);

class SystemState(object):
    def __init__(self):
        # Set initial variables
        self.system_info_cached = False
        self.is_online = False
        self.user_name = getuser()

        # Determine which type of session we are in.
        if os.path.exists('/usr/share/glib-2.0/schemas/zubuntu-mate-live.gschema.override'):
            self.session_type = 'live'
        elif self.user_name[:6] == 'guest-':
            self.session_type = 'guest'
        elif os.path.isfile(os.path.join('/','boot/','kernel7.img')):
            self.session_type = 'pi'
        else:
            self.session_type = 'normal'

        # To inform the user if they are running in BIOS or UEFI mode.
        if os.path.exists("/sys/firmware/efi"):
            self.boot_mode = 'UEFI'
        elif self.session_type == 'pi':
            self.boot_mode = 'Raspberry Pi 2'
        else:
            self.boot_mode = 'BIOS'

        # Create, then spawn threads
        thread1 = Thread(target=self.check_internet_connection)
        thread2 = Thread(target=self.detect_graphics)
        thread3 = Thread(target=self.get_system_info)
        thread1.start()
        thread2.start()
        thread3.start()

    def check_internet_connection(self):
        print('[Network Test] Checking for internet connectivity... ')
        url = "http://archive.ubuntu.com/"
        try:
            response = urllib.request.urlopen(url, timeout=2).read().decode('utf-8')
        except socket.timeout:
            print("[Network Test] -- Socket timed out to URL {0}", format(url))
            self.is_online = False
        except:
            print("[Network Test] -- Could not establish a connection to '{0}'. ".format(url))
            self.is_online = False
        else:
            print("[Network Test] Successfully pinged '{0}' ".format(url))
            self.is_online = True

    def detect_graphics(self):

        # If we're the Raspberry Pi 2, there is nothing to output.
        if self.session_type == 'pi':
            self.graphics_grep = 'Raspberry Pi 2'
            self.graphics_vendor = 'Raspberry Pi 2'
            return

        # TODO: Support dual graphic cards.
        print('[Graphics] Detecting graphics vendor... ')
        try:
            output = subprocess.Popen('lspci | grep VGA', stdout=subprocess.PIPE, shell='True').communicate()[0]
            output = output.decode(encoding='UTF-8')
        except:
            # When 'lspci' does not find a VGA controller (this is the case for the RPi 2)
            print("[Graphics] Couldn't detect a VGA Controller on this system.")
            output = 'Unknown'

        # Scan for and set known brand name.
        if output.find('NVIDIA') != -1:
            self.graphics_vendor = 'NVIDIA'
        elif output.find('AMD') != -1:
            self.graphics_vendor = 'AMD'
        elif output.find('Intel') != -1:
            self.graphics_vendor = 'Intel'
        elif output.find('VirtualBox') != -1:
            self.graphics_vendor = 'VirtualBox'
        else:
            self.graphics_vendor = 'Unknown'

        self.graphics_grep = repr(output)
        self.graphics_grep = self.graphics_grep.split("controller: ",1)[1]
        self.graphics_grep = self.graphics_grep.split("\\n",1)[0]
        print("[Graphics] Detected: {0}".format(self.graphics_grep))

    def get_system_info(self):
        print('[System Info] Caching system info... ')
        try:
            # Use 'inxi' to retrieve the system information.
            self.specs_raw_system = str(subprocess.Popen('inxi -S', stdout=subprocess.PIPE, shell='True').communicate()[0])
            self.specs_raw_machine = str(subprocess.Popen('inxi -M', stdout=subprocess.PIPE, shell='True').communicate()[0])
            self.specs_raw_cpu = str(subprocess.Popen('inxi -C', stdout=subprocess.PIPE, shell='True').communicate()[0])
            self.specs_raw_memory = str(subprocess.Popen('free | grep \'Mem:\' | awk \'{print $2}\'', stdout=subprocess.PIPE, shell='True').communicate()[0]).strip("b'\\n")
            self.specs_raw_drivelist = str(subprocess.Popen('inxi -D', stdout=subprocess.PIPE, shell='True').communicate()[0])
            self.specs_raw_partitions = str(subprocess.Popen('inxi -p', stdout=subprocess.PIPE, shell='True').communicate()[0])
            self.specs_raw_raid = str(subprocess.Popen('inxi -R', stdout=subprocess.PIPE, shell='True').communicate()[0])
            self.specs_raw_optical = str(subprocess.Popen('inxi -d', stdout=subprocess.PIPE, shell='True').communicate()[0])
            self.specs_raw_optical = 'Optical:  ' + '<b>dev:</b> ' + self.specs_raw_optical.split('Optical:')[1]
            self.specs_raw_graphics = str(subprocess.Popen('inxi -G', stdout=subprocess.PIPE, shell='True').communicate()[0])
            self.specs_raw_audio = str(subprocess.Popen('inxi -A', stdout=subprocess.PIPE, shell='True').communicate()[0])
            self.specs_raw_network = str(subprocess.Popen('inxi -i', stdout=subprocess.PIPE, shell='True').communicate()[0])
            self.specs_raw_sensors = str(subprocess.Popen('inxi -s', stdout=subprocess.PIPE, shell='True').communicate()[0])

            # If commands were successfully executed.
            self.system_info_cached = True
            print("[System Info] Successfully cached system information.")

        except:
            print("[System Info] There was a problem running 'inxi'. Is this program no longer installed?")
            return

    def append_system_info(self, webkit, ram_only=False):

        # Cleans up raw data from the command.
        def append_raw(data, label, target_element, existing=False):

          try:
            ## Only show the string after the "System:", "Network:" bit.
            output = data.split(label+':')[1]

            ## Clear out terminal colour codes.
            output = output.replace(' \\x1b[1;34m','<b>')
            output = output.replace('\\x1b[0;37m','</b>')
            output = output.replace(' </b>','')
            output = output.replace(' \\x1b','<br>')
            output = output.replace('[0;37m','')
            output = output.replace('[1;34m','')
            output = output.replace('\\x1b','')
            output = output.replace('[0m\'','')
            output = output.replace('\\n','\n')
            output = output.replace('<b>','<br><b>')
            output = output.split('<br>', 1)[1]
            output = output.strip('          ')

            ## Replace some strings that inxi outputs with something tidier.
            output = output.replace('<br><b>Desktop:</b> N/A','')
            output = output.replace('Mobo:','Motherboard:')
            output = output.replace('model:','Model:')
            output = output.replace('<b>v:','<b>Version:')
            output = output.replace('Bios:','BIOS Vendor:')
            output = output.replace('date:','Date:')
            output = output.replace('cache:','Cache:')
            output = output.replace('clock speeds:','<br><u>Current Clock Speeds:</u>')
            output = output.replace('max:','Max:')
            output = output.replace('<br><b>ID-','<br><br><b>ID-')
            output = output.replace('<br><b>Card-','<br><br><b>Card-')
            output = output.replace('<br><b>Device-','<br><br><b>Device-')
            output = output.replace('size:','Size:')
            output = output.replace('used:','Used:')
            output = output.replace('fs:','File System:')
            output = output.replace('dev:','Device Block:')
            output = output.replace('Features:','<br><b><u>Features:</u></b><br>')
            output = output.replace('features:','Features:')
            output = output.replace('driver:','Drivers:')
            output = output.replace('drivers:','Drivers:')
            output = output.replace('state:','State:')
            output = output.replace('speed:','Speed:')
            output = output.replace('dev-links:','Device Block Links:')
            output = output.replace('multissession:','Multi-Session Support:')
            output = output.replace('audio:','Audio Support:')
            output = output.replace('dvd:','DVD Support:')
            output = output.replace('rw:','Read/Write Support:')
            output = output.replace('duplex:','Duplex:')
            output = output.replace('mac:','MAC Address:')
            output = output.replace('ip:','LAN IP Address:')
            output = output.replace('IF:','Interface:')
            output = output.replace('WAN IP:','Public IP Address:')
            output = output.replace('mobo:','Motherboard:')
            output = output.replace('gpu:','GPU:')
            output = output.replace('cpu:','<br>CPU:')
            output = output.replace('(in rpm)','(in RPM)')
            output = output.replace('devices:','Devices:')
            output = output.replace('<b>Device Block:</b> No optical drives detected.','No optical drives detected.')

            # Write to target element, but only clear if no data is appended here yet.
            if not existing:
                # No information exists in this element yet.
                webkit.execute_script('$("#spec-' + target_element + '").html("")')
            else:
                # Additional commands provide more data for here, add a gap.
                webkit.execute_script('$("#spec-' + target_element + '").append("<br><br>")')

            for line in output.split('\n'):
                webkit.execute_script('$("#spec-' + target_element + '").append("' + line + '")')

          except:
              print('[System Info] No suitable data to process for "' + label + '".')
              if not existing:
                  webkit.execute_script('$("#spec-' + target_element + '").html("No information available.")')

        # If authenticating to retrieve root privileged information about the RAM.
        if ram_only:
            print('[System Info] Authenticating to retrieve RAM details...')
            ram_output = str(subprocess.Popen('pkexec inxi -m', stdout=subprocess.PIPE, shell='True').communicate()[0])
            append_raw(ram_output, 'Memory', 'ram-advanced')
            return

        # Process each category of system information.
        append_raw(self.specs_raw_system, 'System', 'system')
        append_raw(self.specs_raw_machine, 'Machine', 'machine')
        append_raw(self.specs_raw_cpu, 'CPU', 'cpu')
        append_raw(self.specs_raw_drivelist, 'Drives', 'storage')
        append_raw(self.specs_raw_partitions, 'Partition', 'storage', True)
        append_raw(self.specs_raw_raid, 'RAID', 'storage', True)
        append_raw(self.specs_raw_optical, 'Optical', 'optical')
        append_raw(self.specs_raw_graphics, 'Graphics', 'graphics')
        append_raw(self.specs_raw_audio, 'Audio', 'audio')
        append_raw(self.specs_raw_network, 'Network', 'network')
        append_raw(self.specs_raw_sensors, 'Sensors', 'sensors')

        # Add details about UEFI/BIOS boot mode.
        webkit.execute_script('$("#spec-system").append("<br><b>Boot Mode:</b> ' + self.boot_mode + '")')

        # Details for RAM require root privilages, show total capacity instead.
        webkit.execute_script('$("#spec-ram").html("")')
        webkit.execute_script('$("#spec-ram").append("<b>Total:</b> ' + str(round(int(self.specs_raw_memory)/1024/1024,1)) + ' GiB (' + str(round(int(self.specs_raw_memory)/1024)) + ' MiB)")')
        webkit.execute_script('$("#spec-ram").append("<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;' + str(round(int(self.specs_raw_memory)/1000/1000,1)) + ' GB &nbsp;(' + str(round(int(self.specs_raw_memory)/1000)) + ' MB)")')


if __name__ == "__main__":
    set_proc_title()
    app = WelcomeApp()
    systemstate = SystemState()
    print('[Welcome] Application Started.')
    app.run()
