#!/usr/bin/env python3

# Copyright (C) 2015 Martin Wimpress <code@ubuntu-mate.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.


import gettext
import os
import platform
import subprocess
import sys
import urllib.request
from gi.repository import GLib, Notify

from aptdaemon.client import AptClient
from aptdaemon.gtk3widgets import AptErrorDialog, AptConfirmDialog, AptProgressDialog
import aptdaemon.errors
from aptdaemon.enums import *

# i18n
gettext.install("ubuntu-mate-welcome", "/usr/share/locale")

class SimpleApt(object):
    def __init__(self, packages):
        self._timeout=250
        self.packages=packages
        self.update_cache = False
        self.loop = GLib.MainLoop()
        self.client = AptClient()
        print(self.packages)

    def on_error(self, error):
        if isinstance(error, aptdaemon.errors.NotAuthorizedError):
            # Silently ignore auth failures
            return
        elif not isinstance(error, aptdaemon.errors.TransactionFailed):
            # Catch internal errors of the client
            error = aptdaemon.errors.TransactionFailed(ERROR_UNKNOWN,str(error))
        error_dialog = AptErrorDialog(error)
        error_dialog.run()
        error_dialog.hide()

    def on_finished_update(self, trans, exit):
        if exit != "exit-success":
            self.loop.quit()
            sys.exit(1)
        GLib.timeout_add(self._timeout,self.do_install)
        return True

    def do_update(self):
        apt_update = self.client.update_cache()
        apt_update.connect("finished",self.on_finished_update)
        
        update_dialog = AptProgressDialog(apt_update)
        update_dialog.run(close_on_finished=True, show_error=True,
                reply_handler=lambda: True,
                error_handler=self.on_error,
                )
        return False

    def on_finished_install(self, trans, exit):
        self.loop.quit()
        if exit != "exit-success":
            sys.exit(1)

    def do_install(self):
        apt_install = self.client.install_packages(self.packages)
        apt_install.connect("finished", self.on_finished_install)
        install_dialog = AptProgressDialog(apt_install)
        install_dialog.run(close_on_finished=True, show_error=True,
                        reply_handler=lambda: True,
                        error_handler=self.on_error,
                        )
        return False

    def install_packages(self):
        if self.update_cache:
            GLib.timeout_add(self._timeout,self.do_update)
        else:
            GLib.timeout_add(self._timeout,self.do_install)
        self.loop.run()

def add_repo_key(repo_key_url):
    print('Getting ' + repo_key_url)
    if os.path.exists(os.path.join('/', 'tmp', 'pub.key')):
        os.remove(os.path.join('/', 'tmp', 'pub.key'))

    # Download the file from `url` and save it locally under `file_name`:
    with urllib.request.urlopen(repo_key_url) as response, open(os.path.join('/', 'tmp', 'pub.key'), 'wb') as out_file:
        data = response.read() # a `bytes` object
        out_file.write(data)

def add_repo(lines, listname):
    print('Writing ' + os.path.join('/','etc','apt','sources.list.d',listname))
    with open(os.path.join('/','etc','apt','sources.list.d',listname), 'w') as f:
        f.write('\n'.join(lines))

def notify_install_cancelled():
    Notify.init(_('Install cancelled'))
    replace_windowmanager_notify=Notify.Notification.new (_('Install cancelled'),_('The installation of ' + packages + ' has been cancelled.'),'dialog-information')
    replace_windowmanager_notify.show()

def notify_install_success():
    Notify.init(_('Install complete'))
    replace_windowmanager_notify=Notify.Notification.new (_('Install complete'),_('The following software has been correctly installed ' + packages),'dialog-information')
    replace_windowmanager_notify.show()

def notify_install_failed():
    Notify.init(_('Install failed'))
    replace_windowmanager_notify=Notify.Notification.new (_('Install failed'),_('The installation of ' + packages + 'failed.'),'dialog-error')
    replace_windowmanager_notify.show()

if __name__ == "__main__":
    if len(sys.argv) >= 2:
        packages = sys.argv[1].split(',')
    else:
        print('No package(s) supplied')
        sys.exit(1)

    transaction = SimpleApt(packages)
    
    # Perform any pre-install configuration. Basically enabling repositories or
    # adding PPAs.
    if 'adobe-flashplugin' in packages:
        subprocess.call(['apt-add-repository', '--enable-source', '--yes', 'http://archive.canonical.com/ubuntu partner'])
        transaction.update_cache = True
    elif 'skype' in packages:
        subprocess.call(['apt-add-repository', '--enable-source', '--yes', 'http://archive.canonical.com/ubuntu partner'])
        transaction.update_cache = True
    elif 'telegram' in packages:
        subprocess.call(['apt-add-repository', '--enable-source', '--yes', 'ppa:atareao/telegram'])
        transaction.update_cache = True
    elif 'google-chrome-stable' in packages:
        add_repo_key('http://dl.google.com/linux/linux_signing_key.pub')
        subprocess.call(['/usr/bin/apt-key', 'add', os.path.join('/', 'tmp', 'pub.key')])
        lines = ['deb [arch=amd64,i386] http://dl.google.com/linux/chrome/deb/ stable main']
        add_repo(lines, 'google-chrome.list')
        transaction.update_cache = True
    elif 'syncthing' in packages:
        add_repo_key('https://syncthing.net/release-key.txt')
        subprocess.call(['/usr/bin/apt-key', 'add', os.path.join('/', 'tmp', 'pub.key')])
        lines = ['deb http://apt.syncthing.net/ syncthing release']
        add_repo(lines, 'syncthing.list')
        transaction.update_cache = True
    elif 'steam-launcher' in packages:
        add_repo_key('http://repo.steampowered.com/steam/signature.gpg')
        subprocess.call(['/usr/bin/apt-key', 'add', os.path.join('/', 'tmp', 'pub.key')])
        lines = ['deb [arch=amd64,i386] http://repo.steampowered.com/steam/ precise steam',
                 'deb-src [arch=amd64,i386] http://repo.steampowered.com/steam/ precise steam',
                 '']
        add_repo(lines, 'steam.list')
        transaction.update_cache = True
    elif 'spotify-client' in packages:
        subprocess.call(['apt-key', 'adv', '--keyserver', 'keyserver.ubuntu.com', '--recv-keys', '94558F59'])
        
        # Workaround vivid and wily no longer having libgcrypt11 that Spotify
        # requires.
        if codename == 'vivid' or codename == 'wily':
            lines = ['deb http://repository.spotify.com stable non-free',
                     'deb http://security.ubuntu.com/ubuntu utopic-security main']
            packages.append(['libgcrypt11'])
        else:
            lines = ['deb http://repository.spotify.com stable non-free']
        add_repo(lines, 'spotify.list')
        transaction.update_cache = True
    elif 'dropbox' in packages:
        if codename == 'wily':
            codename == 'vivid'

        subprocess.call(['apt-key', 'adv', '--keyserver', 'pgp.mit.edu', '--recv-keys', '5044912E'])
        lines = ['deb http://linux.dropbox.com/ubuntu/ ' + codename + ' main']
        add_repo(lines, 'dropbox.list')
        transaction.update_cache = True
    elif 'virtualbox-4.3' in packages:
        if codename == 'wily':
            codename == 'vivid'
        add_repo_key('https://www.virtualbox.org/download/oracle_vbox.asc')
        subprocess.call(['/usr/bin/apt-key', 'add', os.path.join('/', 'tmp', 'pub.key')])
        lines = ['deb http://download.virtualbox.org/virtualbox/debian ' + codename + ' contrib']
        add_repo(lines, 'virtualbox.list')
        transaction.update_cache = True

    transaction.install_packages()
