#! /usr/bin/python3
# -*- coding:utf-8 -*-
#
# Copyright 2012-2013 "Korora Project" <dev@kororaproject.org>
# Copyright 2013 "Manjaro Linux" <support@manjaro.org>
# Copyright 2014 Antergos
# Copyright 2015-2016 Martin Wimpress <code@flexion.org>
# Copyright 2015-2017 Luke Horwell <luke@ubuntu-mate.org>
#
# Ubuntu MATE Welcome is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ubuntu MATE Welcome is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ubuntu MATE Welcome. If not, see <http://www.gnu.org/licenses/>.
#

""" Welcome screen for Ubuntu MATE """

import gi
gi.require_version("Gdk", "3.0")
gi.require_version("Gtk", "3.0")
gi.require_version("Notify", "0.7")
gi.require_version("WebKit2", "4.0")

import errno
import gettext
import inspect
import json
import locale
import os
import platform
import random
import setproctitle
import signal
import socket
import subprocess
import sys
import time
import webbrowser

import urllib.error
import urllib.parse
import urllib.request
from gi.repository import GLib, Gio, GObject, Gdk, Gtk, Notify, WebKit2
from threading import Thread
from shutil import which


##################################
#  Miscellaneous
##################################
def whereami():
    """ Determine data source """
    current_folder = os.path.dirname( os.path.abspath(inspect.getfile(inspect.currentframe())) )
    if( os.path.exists( os.path.join(current_folder, 'data/' ) ) ):
        dbg.stdout('Welcome', 'Using relative path for data source. Non-production testing.', 1, 0)
        data_path = os.path.join(current_folder, 'data/')
    elif( os.path.exists('/usr/share/ubuntu-mate-welcome/') ):
        dbg.stdout('Welcome', 'Using /usr/share/ubuntu-mate-welcome/ path.', 1, 0)
        data_path = '/usr/share/ubuntu-mate-welcome/'
    else:
        dbg.stdout('Welcome', 'Unable to source the ubuntu-mate-welcome data directory.', 0, 1)
        sys.exit(1)
    return data_path

def notify_send(title, description, icon_path):
    """
    Send system notification to the user.
    """
    try:
        Notify.init(title)
        notification=Notify.Notification.new(title, description, icon_path)
        notification.show()
    except Exception as e:
        dbg.stdout("Notify", "Exception while sending notification: " + str(e), 0, 1)

def run_external_command(command, with_shell=False):
    # Runs external commands and cleans up the output.
    if with_shell:
        raw = str(subprocess.Popen(command, stdout=subprocess.PIPE, shell=True).communicate()[0])
    else:
        raw = str(subprocess.Popen(command, stdout=subprocess.PIPE).communicate()[0])
    output = raw.replace("b'","").replace('b"',"").replace("\\n'","").replace("\\n","\n")
    return output

##################################
#  Translations Framework & Strings
##################################
class Translations(object):
    def __init__(self, data_path):
        # Pages that do not want to be translated.
        self.excluded_pages = ['message.html']

        # Determine which locale to use
        if arg.locale:
            self.locale = arg.locale
        else:
            try:
                self.locale = str(locale.getlocale()[0])
            except Exception:
                dbg.stdout("i18n", "Could not get system locale information! Falling back to 'en_US'.")
                self.locale = "en_US"

        # Determine if localized pages exist, or fallback to original pages.
        def get_pages_path():
            if os.path.exists(os.path.join(data_path, 'i18n', self.locale)):
                self.localized = True
                self.relative_i18n = True
                dbg.stdout('i18n', 'Locale Set: ' + self.locale + ' (using relative path)', 1, 0)
                return os.path.join(data_path, 'i18n', self.locale)
            elif (os.path.exists(os.path.join('/usr/share/ubuntu-mate-welcome/i18n/', self.locale))):
                self.localized = True
                self.relative_i18n = False
                dbg.stdout('i18n', 'Locale Set: ' + self.locale + ' (using /usr/share/ path)', 1, 0)
                return os.path.join('/usr/share/ubuntu-mate-welcome/i18n/', self.locale)
            else:
                self.localized = False
                self.relative_i18n = False
                dbg.stdout('i18n', 'Locale Not Available: ' + self.locale + ' (using en_US instead)', 1, 1)
                return data_path

        self.pages_dir = get_pages_path()

        # Should this locale not exist, try a generic one. (e.g. "en_GB" → "en")
        if self.pages_dir == data_path:
            self.localized = False
            self.locale = self.locale.split('_')[0]
            self.pages_dir = get_pages_path()
        else:
            self.localized = True

        # Validate all the i18n pages so we have the same structure as the original.
        page_was_lost = False
        if not self.pages_dir == data_path:
            for page in os.listdir(data_path):
                if page[-5:] == '.html':
                    if os.path.exists(os.path.join(self.pages_dir, page)):
                        dbg.stdout('i18n', 'Page Verified: ' + page, 2, 2)
                    else:
                        if page not in self.excluded_pages:
                            page_was_lost = True
                            dbg.stdout('i18n', 'Page Missing: ' + page, 2, 1)
        if page_was_lost:
            dbg.stdout('i18n', 'One or more translation pages are missing! Falling back to "en_US".', 0, 1)
            self.pages_dir = data_path
            self.localized = False
        else:
            dbg.stdout('i18n', 'All translated i18n pages found.', 1, 2)

        # Sets the path for resources (img/css/js)
        if self.localized:
            # E.g. data/i18n/en_GB/*.html → data/
            self.res_dir = '../../'
        else:
            # E.g. data/*.html → data/
            self.res_dir = ''

        # Initalise i18n for Python translations.
        if self.relative_i18n:
            i18n_path = '/usr/share/locale/'
        else:
            i18n_path = os.path.join(data_path, 'locale/')

        global t, _
        dbg.stdout('i18n', 'Using locale for gettext: ' + self.locale, 1, 0)
        dbg.stdout('i18n', 'Using path for gettext: ' + i18n_path, 1, 0)
        try:
            t = gettext.translation('ubuntu-mate-welcome', localedir=i18n_path, languages=[self.locale], fallback=True)
            _ = t.gettext
            dbg.stdout('i18n', 'Translation found for gettext.', 1, 2)
        except:
            dbg.stdout('i18n', 'No translation exists for gettext. Using default.', 1, 2)
            t = gettext.translation('ubuntu-mate-welcome', localedir='/usr/share/locale/', fallback=True)
            _ = t.gettext


##################################
#  WebKit + Python Communications
##################################
class AppView(WebKit2.WebView):
    def __init__(self):
        # WebKit2 Initalisation
        webkit = WebKit2
        webkit.WebView.__init__(self)

        # Connect signals to application
        self.connect('load-changed', self._load_changed_cb)
        self.connect('notify::title', self._title_changed_cb)
        self.connect('context-menu', self._context_menu_cb)

        # Enable keyboard navigation
        self.get_settings().set_enable_spatial_navigation(True)
        self.get_settings().set_enable_caret_browsing(True)

        # Show console messages in stdout if we're debugging.
        if dbg.verbose_level == 2:
            self.get_settings().set_enable_write_console_messages_to_stdout(True)

        # Set up zoom to match rest of system font
        self.set_zoom_level(systemstate.zoom_level)
        dbg.stdout('Welcome', 'Setting zoom level to: ' + str(systemstate.zoom_level), 1, 0)

        # Perform a smooth transition for footer icons.
        self.do_smooth_footer = False

    def _push_config(self):
        ### Global - On all pages ###

        # Do not show footer links on splash or software page.
        if not arg.jump_software_page:
            if not app.current_page == 'splash.html' and not app.current_page == 'software.html':
                app.update_page('#footer-global-left', 'html', app.footer_left)

        # Do not show the Close button in Boutique mode.
        if not arg.jump_software_page:
            app.update_page('#footer-global-right', 'html', app.footer_close)

        # Show the "Scroll to Top" button, excluding the Boutique which has its own button.
        if not app.current_page == "software.html":
            app.update_page("#navigation-right", "append", '<button id="scroll-top" class="navigation-button" onclick="backToTop()" style="display:none" title="' + _("Scroll Up") + '"><span class="fa fa-chevron-up"></span></button>')

        # If this is a live session, adapt the UI.
        if systemstate.session_type == 'live':
            if app.current_page == 'index.html' or app.current_page == 'gettingstarted.html':
                app.update_page('.live-session-hide', 'hide')
                app.update_page('.live-session-only', 'show')
        else:
            app.update_page('.live-session-hide', 'show')
            app.update_page('.live-session-only', 'hide')

        # Display warnings if the user is not connected to the internet.
        if systemstate.is_online:
            app.update_page('.offline', 'hide')
            app.update_page('.online', 'show')
        else:
            app.update_page('.offline', 'show')
            app.update_page('.online', 'hide')

        # Smoothly fade in the footer links between pages.
        #   splash → index
        #   index ← → software
        if self.do_smooth_footer or app.current_page == 'software.html':
            self.do_smooth_footer = False
            app.update_page('#footer-left', 'hide')
            app.update_page('#footer-left', 'fadeIn')
            app.update_page('#navigation-right', 'hide')
            app.update_page('#navigation-right', 'fadeIn')

        # Individual Page Actions
        ### Main Menu ###
        if app.current_page == 'index.html':
            app.update_page('#os_version', 'html', systemstate.os_version)

            # Buttons (IDs) to be displayed
            btns = [ 'introduction', 'features', 'gettingstarted',
                     'getinvolved', 'shop', 'donate',
                     'community', 'chatroom', 'software', 'open-at-start'
                   ]

            # Show Welcome at login state
            if systemstate.autostart:
                app.update_page('#autostart', 'addClass', 'fa-check-square')
                app.update_page('#autostart', 'removeClass', 'fa-square')
            else:
                app.update_page('#autostart', 'removeClass', 'fa-check-square')
                app.update_page('#autostart', 'addClass', 'fa-square')

            # Disable features that are unavailable to guests.
            if systemstate.session_type == 'guest':
                btns.remove('gettingstarted')
                btns.remove('software')
                btns.remove('open-at-start')
                app.update_page('#introduction', 'addClass', 'btn-success')
                app.update_page('#community', 'addClass', 'btn-success')

            # Raspberry Pi button
            if systemstate.session_type == 'pi':
                btns.append('raspberry-pi')

            # Swap software for install button in live sessions.
            if systemstate.session_type == 'live':
                btns.remove('gettingstarted')
                btns.remove('software')
                btns.remove('open-at-start')
                btns.append('install-guide')
                btns.append('install')

            # Fade in the menu buttons.
            for btn_id in btns:
                app.update_page('#'+btn_id, 'fadeIn')

            # Check whether the system is subscribed for receiving more up-to-date versions of Welcome.
            app.update_page('#update-subscribing', 'hide')
            if not systemstate.updates_subscribed:
                if systemstate.is_online:
                    app.update_page('#update-notification', 'fadeIn', 'slow')
            else:
                app.update_page('#update-notification', 'hide')

            # Disable install button on installed systems.
            if not which("ubiquity"):
                app.update_page("#install", "prop", "disabled", "true")

        ### Splash ###
        if app.current_page == 'splash.html':
            self.do_smooth_footer = True
            # Determine which screen to show after the splash screen.
            if systemstate.session_type == 'live':
                self.run_javascript('var splashNextPage = "hellolive"')
                self.run_javascript('var quick_splash = true')
            elif systemstate.session_type == 'guest':
                self.run_javascript('var splashNextPage = "helloguest"')
                self.run_javascript('var quick_splash = true')
            else:
                self.run_javascript('var splashNextPage = "index"')
                self.run_javascript('var quick_splash = false')
                app.update_page('#skip-btn', 'fadeIn', 'fast')

            # Smoothly fade footer when entering main menu.
            self.splash_finished = True

        ### Chat Page ###
        if app.current_page == 'chatroom.html':
            if os.path.exists("/usr/bin/hexchat"):
                app.update_page('.hexchat', 'show')
                app.update_page('.webchat', 'hide')
            else:
                app.update_page('.hexchat', 'hide')
                app.update_page('.webchat', 'show')

        ### Getting Started Page ###
        if app.current_page == 'gettingstarted.html':
            # Rename the page title when running in a live session.
            if systemstate.session_type == "live":
                app.update_page("#navigation-title", "html", _("Installation Guide"))

            # Display information tailored to graphics vendor (Getting Started / Drivers)
            self.run_javascript('var graphicsVendor = "' + systemstate.graphics_vendor + '";')
            self.run_javascript('var graphicsGrep = "' + systemstate.graphics_grep + '";')
            app.update_page('#boot-mode', 'html', systemstate.boot_mode)

            # Update any applications featured on these pages.
            dynamicapps.update_app_status(self, 'hardinfo')
            dynamicapps.update_app_status(self, 'gparted')
            dynamicapps.update_app_status(self, 'gnome-disk-utility')
            dynamicapps.update_app_status(self, 'mate-disk-usage-analyzer')
            dynamicapps.update_app_status(self, 'mate-system-monitor')
            dynamicapps.update_app_status(self, 'psensor')
            dynamicapps.update_app_status(self, 'boot-repair')
            dynamicapps.update_app_status(self, 'codecs')
            dynamicapps.update_app_status(self, 'firmware')
            dynamicapps.update_app_status(self, 'hp-printer')
            dynamicapps.update_app_status(self, 'solaar')
            dynamicapps.update_app_status(self, 'keyboard-chinese')
            dynamicapps.update_app_status(self, 'keyboard-japanese')
            dynamicapps.update_app_status(self, 'keyboard-korean')
            dynamicapps.update_app_status(self, 'caja-share')
            dynamicapps.update_app_status(self, 'libdvdcss2')
            dynamicapps.update_app_status(self, 'xscreensaver')
            dynamicapps.update_app_status(self, 'xthemes')
            dynamicapps.update_app_status(self, 'wallpapers')
            dynamicapps.update_app_status(self, 'polychromatic')
            dynamicapps.update_app_status(self, 'razer-drivers')

        ### Raspberry Pi Page ###
        if app.current_page == 'rpi.html':
            # Check file system resize flag.
            systemstate.rpi_resize('check', self)

        ### Donate ###
        if app.current_page == 'donate.html':
            # Pass translatable short-hand month strings for the supporters grid.
            self.run_javascript('short_jan = "' + _("Jan") + '"')
            self.run_javascript('short_feb = "' + _("Feb") + '"')
            self.run_javascript('short_mar = "' + _("Mar") + '"')
            self.run_javascript('short_apr = "' + _("Apr") + '"')
            self.run_javascript('short_may = "' + _("May") + '"')
            self.run_javascript('short_jun = "' + _("Jun") + '"')
            self.run_javascript('short_jul = "' + _("Jul") + '"')
            self.run_javascript('short_aug = "' + _("Aug") + '"')
            self.run_javascript('short_sep = "' + _("Sep") + '"')
            self.run_javascript('short_oct = "' + _("Oct") + '"')
            self.run_javascript('short_nov = "' + _("Nov") + '"')
            self.run_javascript('short_dec = "' + _("Dec") + '"')

        ### Message ###
        if app.current_page == 'message.html':
            """ Displays one-time information. """
            msg_id = app.msg_to_display
            # Which message to display?
            if not msg_id:
                dbg.stdout("Welcome", "No message ID set! Returning to main menu.", 0, 1)
                app.webkit.run_javascript("smoothPageFade('index.html')")
                return
            elif msg_id == "boutique-on-other-distro":
                nav_title = _("Unsupported Distribution")
                body_title = _("Your mileage may wary.")
                body_text = _("Software Boutique is designed for Ubuntu MATE, but it appears you are " + \
                       "running a different distribution.") + '</p><p>' + _("While a large selection of software " + \
                       "will work on other Ubuntu-based distributions, we cannot guarantee " + \
                       "our featured picks will work flawlessly on your system.") + '</p><p>' + \
                       '<span class="fa fa-info-circle"></span> ' + _("This message will not be shown again.")
                image = "img/welcome/boutique-on-other-distro.png"
                target = "software.html"
            else:
                dbg.stdout("Welcome", "Unknown message ID: '" + msg_id + "' - Returning to main menu.", 0, 1)
                app.webkit.run_javascript("smoothPageFade('index.html')")
                return

            # Push message contents to page.
            app.update_page('#navigation-title', 'html', nav_title)
            app.update_page('#message-title', 'html', body_title)
            app.update_page('#message-body', 'html', body_text)
            app.update_page('#message-image', 'html', "<img src='{0}'/>".format(trans.res_dir + image))
            app.update_page('#message-link', 'html', "<button class='btn btn-success' onclick=\"smoothPageFade(\'{0}\')\">{1}</button>".format(target, _("Continue")))

    def _title_changed_cb(self, view, frame):
        title = self.get_title()
        if title != 'null' and title != '' and title != None:
            dbg.stdout('Welcome', 'Command: ' + title, 2, 4)
            self._do_command(title)

    def _load_changed_cb(self, view, frame):
        uri = str(self.get_uri())
        app.current_page = uri.rsplit('/', 1)[1]

        ### Tweaks to execute before fully loading the page. Prevents flicker in some cases. ###
        # Adapt the header/footer if a different theme is in use.
        def light_theme():
            app.update_page('#navigation', 'css', 'color', 'black')
            app.update_page('#navigation a', 'css', 'color', 'black')
            app.update_page('#footer', 'css', 'color', 'black')
            app.update_page('#footer a', 'css', 'color', 'black')
            app.update_page('.btn-inverse', 'removeClass', 'btn-inverse')

        if systemstate.theme == 'BlackMATE':
            app.update_page('#navigation', 'css', 'background-color', '#3D3D3F')
            app.update_page('#footer', 'css', 'background-color', '#3D3D3F')
        elif systemstate.theme == 'BlueMenta':
            app.update_page('#navigation', 'css', 'background-color', '#D2D2D2')
            app.update_page('#footer', 'css', 'background-color', '#D2D2D2')
            light_theme()
        elif systemstate.theme == 'Blue-Submarine':
            app.update_page('#navigation', 'css', 'background-color', '#2C404F')
            app.update_page('#footer', 'css', 'background-color', '#2C404F')
        elif systemstate.theme == 'GreenLaguna':
            app.update_page('#navigation', 'css', 'background-color', '#EAF0E8')
            app.update_page('#footer', 'css', 'background-color', '#EAF0E8')
            light_theme()
        elif systemstate.theme == 'ContrastHigh':
            app.update_page('#navigation', 'css', 'background-color', 'white')
            app.update_page('#footer', 'css', 'background-color', 'white')
            light_theme()
        elif systemstate.theme == 'ContrastHighInverse':
            app.update_page('#navigation', 'css', 'background-color', 'black')
            app.update_page('#footer', 'css', 'background-color', 'black')
        elif systemstate.theme == 'Menta':
            app.update_page('#navigation', 'css', 'background-color', '#D2D2D2')
            app.update_page('#footer', 'css', 'background-color', '#D2D2D2')
            light_theme()
        elif systemstate.theme == 'Radiant-MATE':
            app.update_page('#navigation', 'css', 'background-color', '#DFD7CF')
            app.update_page('#footer', 'css', 'background-color', '#DFD7CF')
            light_theme()
        elif systemstate.theme == 'TraditionalGreen' or systemstate.theme == 'TraditionalOk':
            app.update_page('#navigation', 'css', 'background-color', '#E7E6E5')
            app.update_page('#footer', 'css', 'background-color', '#E7E6E5')
            light_theme()
        elif systemstate.theme == 'TraditionalOkTest':
            app.update_page('#navigation', 'css', 'background-color', '#868883')
            app.update_page('#footer', 'css', 'background-color', '#868883')

        # Push contents to page when finished loading.
        if not self.is_loading():
            dbg.stdout('Welcome', 'Page: ' + app.current_page + '\n      ' + uri, 2, 4)
            self._push_config()

    def _context_menu_cb(self, webview, menu, event, htr, user_data=None):
        # Disable context menu.
        return True

    def _do_command(self, cmd):
        if cmd == 'autostart':
            systemstate.autostart_toggle()
            self._push_config()
        elif cmd == 'install':
            if not which("ubiquity"):
                print("Installation cannot be started as Ubiquity is missing.")
            else:
                subprocess.Popen(['ubiquity', 'gtk_ui'])
        elif cmd == 'backup':
            subprocess.Popen(['deja-dup-preferences'])
        elif cmd == 'chatroom':
            subprocess.Popen(['hexchat','IRC://irc.freenode.net/ubuntu-mate'])
        elif cmd == 'control':
            subprocess.Popen(['mate-control-center'])
        elif cmd == 'drivers':
            subprocess.Popen(['software-properties-gtk','--open-tab=4'])
        elif cmd == 'firewall':
            subprocess.Popen(['gufw'])
        elif cmd == 'language':
            subprocess.Popen(['gnome-language-selector'])
        elif cmd == 'users':
            subprocess.Popen(['users-admin'])
        elif cmd == 'quit':
            app.close()
        elif cmd == 'tweak':
            subprocess.Popen(['mate-tweak'])
        elif cmd == 'update':
            subprocess.Popen(['update-manager'])
        elif cmd == 'printers':
            subprocess.Popen(['system-config-printer'])
        elif cmd == 'gparted':
            subprocess.Popen(['gparted-pkexec'])
        elif cmd == 'sysmonitor':
            subprocess.Popen(['mate-system-monitor'])
        elif cmd.startswith('run?'):
            subprocess.Popen([cmd[4:]])
        elif cmd.startswith('link?'):
            webbrowser.open_new_tab(cmd[5:])
        elif cmd == 'checkInternetConnection':
            systemstate.check_internet_connection()
            if systemstate.is_online:
                app.update_page('.offline', 'hide')
                app.update_page('.online', 'show')
            else:
                app.update_page('.offline', 'show')
                app.update_page('.online', 'hide')
        elif cmd == 'resize-rpi':
            systemstate.rpi_resize('do-resize', self)
        elif cmd == 'reboot-rpi':
            systemstate.rpi_resize('reboot')
        elif cmd == 'subscribe-updates':
            dbg.stdout('Welcome', 'Subscribing to Ubuntu MATE Welcome Updates...', 0, 3)
            app.update_page('#update-notification', 'hide')
            app.update_page('#update-subscribing', 'show')
            dynamicapps.modify_app(self, 'install', 'ubuntu-mate-welcome')
            # Verify if the PPA was successfully added.
            if os.path.exists(systemstate.welcome_ppa_file):
                if os.path.getsize(systemstate.welcome_ppa_file) > 0:
                    dbg.stdout('Welcome', 'Success - Welcome PPA Added! Restarting application...', 0, 2)
                    os.execv(__file__, sys.argv)
            else:
                dbg.stdout('Welcome', 'Failed - Welcome PPA not detected!', 0, 1)
                app.update_page('#update-subscribing', 'hide')
                app.update_page('#update-notification', 'show')
        elif cmd == 'init-system-info':
            systemstate.get_system_info(self)
        elif cmd.startswith('search'):
            keywords = cmd.split('?')[1]
            dynamicapps.perform_search(self, keywords)
        elif cmd.startswith('set-pref'):
            key = cmd.split('?')[1]
            value = cmd.split('?')[2]
            pref.set(key, value)
        elif cmd.startswith('toggle-pref'):
            key = cmd.split('?')[1]
            pref.toggle(key)
            pref.refresh_pref_page(key)
            queue.refresh_page_state()
        elif cmd.startswith('clipboard'):
            var = cmd.split('?')[1]
            systemstate.copy_to_clipboard(var)
        elif cmd.startswith('message'):
            app.msg_to_display = cmd.split('?')[1]
            self.run_javascript("smoothPageFade('message.html')")
        elif cmd == 'list-repos':
            dynamicapps.populate_repos()
        else:
            dbg.stdout('Welcome', 'Unknown command: ' + cmd, 0, 1)


##################################
#  Welcome Main Application
##################################

class WelcomeApp(object):
    def __init__(self):
        # Set variables
        self.current_page = ""
        self.webkit = None
        self.load_app()

        ## Social Links ##
        self.footer_left = '<div id="social" class="pull-left"> \
        <button onclick="cmd(\'link?https://ubuntu-mate.org\')" title="' + _("Ubuntu MATE Website") + '"><img src="' + trans.res_dir + 'img/welcome/ubuntu-mate-icon.svg"></button> \
        <button onclick="cmd(\'link?https://plus.google.com/communities/108331279007926658904\')" title="Google+"><img src="' + trans.res_dir + 'img/social/google+.svg"></button> \
        <button onclick="cmd(\'link?https://www.facebook.com/UbuntuMATEedition/\')" title="Facebook"><img src="' + trans.res_dir + 'img/social/facebook.svg"></button> \
        <button onclick="cmd(\'link?https://twitter.com/ubuntu_mate\')" title="Twitter"><img src="' + trans.res_dir + 'img/social/twitter.svg"></button> \
        <button onclick="cmd(\'link?https://ubuntu-mate.org/donate/\')" title="' + _("Donate to Ubuntu MATE") + '"><img src="' + trans.res_dir + 'img/welcome/donate.svg"></button> \
        </div>'
        self.footer_close = '<button onclick="cmd(\'quit\')" class="btn btn-inverse">' + _("Close") + '&zwnj;</button>'

    def load_app(self):
        # Slightly different attributes if "--software-only" is activated.
        if arg.jump_software_page:
            title = string.boutique
            width = 900
            height = 600
            load_file = 'splash-boutique.html'
        else:
            title = _("Welcome")
            width = 800
            height = 552
            load_file = 'splash.html'

        # Enlarge the window should the text be any larger.
        if systemstate.zoom_level == 1.1:
            width = width + 20
            height = height + 20
        elif systemstate.zoom_level == 1.2:
            width = width + 60
            height = height + 40
        elif systemstate.zoom_level == 1.3:
            width = width + 100
            height = height + 60
        elif systemstate.zoom_level == 1.4:
            width = width + 130
            height = height + 100
        elif systemstate.zoom_level == 1.5:
            width = width + 160
            height = height + 120

        # Jump to a specific page for testing purposes.
        if arg.jump_to:
            load_file = arg.jump_to + '.html'

        # Build window
        w = Gtk.Window()
        w.set_position(Gtk.WindowPosition.CENTER)
        w.set_wmclass('ubuntu-mate-welcome', 'ubuntu-mate-welcome')
        w.set_title(title)

        # http://askubuntu.com/questions/153549/how-to-detect-a-computers-physical-screen-size-in-gtk
        s = Gdk.Screen.get_default()
        if s.get_height() <= 600:
            w.set_size_request(768, 528)
        else:
            w.set_size_request(width, height)

        icon_dir = os.path.join(data_path, 'img', 'welcome', 'ubuntu-mate-icon.svg')
        w.set_icon_from_file(icon_dir)

        # Build WebKit2 container
        self.webkit = AppView()

        # Load the starting page
        path = os.path.abspath(os.path.join(trans.pages_dir, load_file))
        uri = 'file://' + urllib.request.pathname2url(path)
        self.webkit.load_uri(uri)

        # Build scrolled window widget and add our appview container
        sw = Gtk.ScrolledWindow()
        sw.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)
        sw.add(self.webkit)

        # Build an autoexpanding box and add our scrolled window
        b = Gtk.VBox(homogeneous=False, spacing=0)
        b.pack_start(sw, expand=True, fill=True, padding=0)

        # Add the box to the parent window and show
        w.add(b)
        w.connect('delete-event', self.close)
        w.show_all()

        self._window = w

    def run(self):
        signal.signal(signal.SIGINT, signal.SIG_DFL)
        Gtk.main()

    def close(self, window=None, event=None):
        dbg.stdout('Welcome', 'Application Closed', 0, 0)
        Gtk.main_quit()
        exit(0)

    def update_page(self, element, function, parm1=None, parm2=None):
        """ Runs a JavaScript jQuery function on the page,
            ensuring correctly parsed quotes. """
        if parm1 and parm2:
            self.webkit.run_javascript('$("' + element + '").' + function + "('" + parm1.replace("'", '\\\'') + "', '" + parm2.replace("'", '\\\'') + "')")
        if parm1:
            self.webkit.run_javascript('$("' + element + '").' + function + "('" + parm1.replace("'", '\\\'') + "')")
        else:
            self.webkit.run_javascript('$("' + element + '").' + function + '()')


class Debug(object):
    def __init__(self):
        self.verbose_level = 0

    def stdout(self, item, info, verbosity=0, colour=0):
        # Only colourise output if running in a real terminal.
        if sys.stdout.isatty():
            end = '\033[0m'
            if colour == 1:            # Failure (Red)
                start = '\033[91m'
            elif colour == 2:          # Success (Green)
                start = '\033[92m'
            elif colour == 3:          # Action (Yellow)
                start = '\033[93m'
            elif colour == 4:          # Debug (Blue)
                start = '\033[96m'
            else:                      # Normal/Misc (White)
                start = '\033[0m'

        # Ignore colours when redirected or piped.
        else:
            start = ''
            end   = ''

        # Output the message depending how detailed it is.
        if self.verbose_level >= verbosity:
            print(start + '[' + item + '] ' + info, end)


class SystemState(object):
    def __init__(self):
        # Set default variables
        self.is_online = False
        self.updates_subscribed = False
        self.rpi_resize_pending = False
        self.welcome_version = 'Unknown'

        # Get user details.
        self.user_name = GLib.get_user_name()

        # Full path to binary
        self._welcome_bin_path = os.path.abspath(inspect.getfile(inspect.currentframe()))

        # User's autostart directory and full path to autostart symlink.
        # Used for systemstate.autostart_toggle() function.
        self._autostart_dir = os.path.expanduser('~/.config/autostart/')
        self._autostart_path = os.path.expanduser(os.path.join(self._autostart_dir, 'ubuntu-mate-welcome.desktop'))
        self.autostart = self.autostart_check()

        # Get current architecture of system.
        # Outputs 'i386', 'amd64', etc - Based on packages instead of kernel (eg. i686, x86_64).
        self.arch = str(subprocess.Popen(['dpkg','--print-architecture'], stdout=subprocess.PIPE).communicate()[0]).strip('\\nb\'')

        # Get current version / codename of Ubuntu MATE in use.
        self.os_version = platform.dist()[1]    # → 14.04, 15.10, 16.04
        self.codename = platform.dist()[2]      # → trusty, wily, xenial

        # Are we running in Ubuntu MATE?
        self.is_ubuntu_mate = True
        #~ if not self.apt_cache['ubuntu-mate-desktop'].is_installed or not self.apt_cache['ubuntu-mate-core'].is_installed:
            #~ if os.environ.get('DESKTOP_SESSION') != "mate":
                #~ self.is_ubuntu_mate = False

        # Determine which type of session we are in.
        if os.path.exists('/usr/share/glib-2.0/schemas/zubuntu-mate-live.gschema.override'):
            self.session_type = 'live'
        elif self.user_name[:6] == 'guest-':
            self.session_type = 'guest'
        elif os.path.isfile(os.path.join('/','boot/','kernel7.img')):
            self.session_type = 'pi'
        else:
            self.session_type = 'normal'

        # To inform the user if they are running in BIOS or UEFI mode.
        if os.path.exists("/sys/firmware/efi"):
            self.boot_mode = 'UEFI'
        elif self.session_type == 'pi':
            self.boot_mode = 'Raspberry Pi'
        elif self.arch == 'powerpc':
            self.boot_mode = 'Yaboot'
        else:
            self.boot_mode = 'BIOS'

        # Multithread to prevent holding up program execution.
        thread1 = Thread(target=self.check_internet_connection)
        thread2 = Thread(target=self.detect_graphics)
        thread1.start()
        thread2.start()

        # Check whether Welcome is subscribed for updates.
        self.welcome_ppa_file = '/etc/apt/sources.list.d/ubuntu-mate-dev-ubuntu-welcome-' + self.codename + '.list'
        if os.path.exists(self.welcome_ppa_file):
            if os.path.getsize(self.welcome_ppa_file) > 0:
                self.updates_subscribed = True

        # Accessibility - Enlarge/shrink text based on Font DPI set by the user.
        if arg.font_dpi_override:
            font_dpi = arg.font_dpi_override
        else:
            if self.is_ubuntu_mate:
                try:
                    font_gsettings = Gio.Settings.new('org.mate.font-rendering')
                    font_value = font_gsettings.get_value('dpi')
                    font_dpi = int(float(str(font_value)))
                    dbg.stdout('Welcome', 'Font DPI is: ' + str(font_dpi), 1, 0)
                except:
                    font_dpi = 96
                    dbg.stdout('Welcome', "Couldn't retrieve font DPI. Using default value of " + str(font_dpi), 0, 1)
            else:
                font_dpi = 96
                dbg.stdout('Welcome', "Refusing to retrieve font DPI on non-Ubuntu MATE system. Using default.", 1, 1)

        if font_dpi < 50:
            dbg.stdout('Welcome', 'DPI below 50. Out of range..', 0, 1)
            font_dpi = 96
        elif font_dpi > 500:
            dbg.stdout('Welcome', 'DPI over 500. Out of range.', 0, 1)
            font_dpi = 96

        zoom_level = 1.0
        if font_dpi <= 80:
            zoom_level = 0.75
        elif font_dpi <= 87:
            zoom_level = 0.85
        elif font_dpi <= 94:
            zoom_level = 0.9
        elif font_dpi <= 101:
            zoom_level = 1.0    # Default DPI for fresh install is 96.
        elif font_dpi <= 108:
            zoom_level = 1.1
        elif font_dpi <= 115:
            zoom_level = 1.2
        elif font_dpi <= 122:
            zoom_level = 1.3
        elif font_dpi <= 129:
            zoom_level = 1.4
        elif font_dpi >= 130:
            zoom_level = 1.5

        self.dpi = font_dpi
        self.zoom_level = zoom_level

        # For adjusting the colours for other default themes.
        if self.is_ubuntu_mate:
            try:
                dconf = Gio.Settings.new('org.mate.interface')
                self.theme = str(dconf.get_value('gtk-theme')).strip("'")
            except:
                self.theme = 'Ambiant-MATE'
        else:
            self.theme = 'Ambiant-MATE'

    def autostart_check(self):
        # Ensure our autostart directories exist
        if not os.path.exists(self._autostart_dir):
            try:
                os.makedirs(self._autostart_dir)
            except OSError as err:
                dbg.stdout('Welcome', 'Error while checking autostart directory: ' + str(err), 0, 1)
                pass

        # Set boolean if the autostart file exists.
        if os.path.exists(self._autostart_path):
            return True
        else:
            return False

    def autostart_toggle(self):
        if not os.path.exists(self._autostart_path):
            # create the autostart symlink
            try:
                os.symlink('/usr/share/applications/ubuntu-mate-welcome.desktop', self._autostart_path)
            except OSError as err:
                dbg.stdout('Welcome', 'Error while enabling autostart: ' + str(err), 0, 1)
                pass

        elif os.path.exists(self._autostart_path):
            # remove the autostart symlink
            try:
                os.unlink(self._autostart_path)
            except OSError as err:
                dbg.stdout('Welcome', 'Error while disabling autostart: ' + str(err), 0, 1)
                pass

        self.autostart = self.autostart_check()
        dbg.stdout('Welcome', 'Auto start toggled to: ' + str(self.autostart), 1, 2)

    def check_internet_connection(self):
        url = "http://archive.ubuntu.com/"
        dbg.stdout('Network Test', 'Establishing a connection test to "' + url + '"', 1, 3)

        if arg.simulate_no_connection:
            dbg.stdout('Network Test', 'Simulation flag: Forcing no connection presence. Retrying will reset this.', 0, 1)
            arg.simulate_no_connection = False
            self.is_online = False
            return

        if arg.simulate_force_connection:
            dbg.stdout('Network Test', 'Simulation flag: Forcing a connection presence.', 0, 2)
            dbg.stdout('Network Test', 'WARNING: Do not attempt to install/remove software offline as this may cause problems!', 0, 1)
            arg.simulate_connection = False
            self.is_online = True
            return

        try:
            response = urllib.request.urlopen(url, timeout=2).read().decode('utf-8')
        except socket.timeout:
            dbg.stdout('Network Test', 'Failed. Socket timed out to URL: ' + url, 0, 1)
            self.is_online = False
        except:
            dbg.stdout('Welcome', "Couldn't establish a connection: " + url, 0, 1)
            self.is_online = False
        else:
            dbg.stdout('Welcome', 'Successfully pinged: ' + url, 1, 2)
            self.is_online = True

    def detect_graphics(self):
        # If we're the Raspberry Pi, there is nothing to output.
        if self.session_type == 'pi':
            self.graphics_grep = 'Raspberry Pi'
            self.graphics_vendor = 'Raspberry Pi'
            return

        # TODO: Support dual graphic cards.
        dbg.stdout('Specs', 'Detecting graphics vendor... ', 1, 3)
        try:
            output = subprocess.Popen('lspci | grep VGA', stdout=subprocess.PIPE, shell='True').communicate()[0]
            output = output.decode(encoding='UTF-8')
        except:
            # When 'lspci' does not find a VGA controller (this is the case for the RPi 2)
            dbg.stdout('Specs', "Couldn't detect a VGA Controller on this system.", 0, 1)
            output = 'Unknown'

        # Scan for and set known brand name.
        if output.find('NVIDIA') != -1:
            self.graphics_vendor = 'NVIDIA'
        elif output.find('AMD') != -1:
            self.graphics_vendor = 'AMD'
        elif output.find('Intel') != -1:
            self.graphics_vendor = 'Intel'
        elif output.find('VirtualBox') != -1:
            self.graphics_vendor = 'VirtualBox'
        else:
            self.graphics_vendor = 'Unknown'

        self.graphics_grep = repr(output)
        self.graphics_grep = self.graphics_grep.split("controller: ",1)[1]
        self.graphics_grep = self.graphics_grep.split("\\n",1)[0]
        dbg.stdout('Specs', 'Detected: ' + str(self.graphics_grep), 1, 2)

    def get_system_info(self, webkit):
        dbg.stdout('Specs', 'Gathering system specifications...', 0, 3)

        # Prefixes for translation
        mb_prefix = _("MB")
        mib_prefix = _("MiB")
        gb_prefix = _("GB")
        gib_prefix = _("GiB")

        # Start collecting advanced system information in the background.
        # (Runs in own thread to prevent holding up screen)
        inxi_thread = Thread(target=self.get_inxi_info)
        inxi_thread.start()

        # Append a failure symbol beforehand in event something goes horribly wrong.
        stat_error_msg = _("Could not gather data.")
        html_tag = '<button data-toggle=\'tooltip\' data-placement=\'top\' title=\'' + stat_error_msg + '\'><span class=\'fa fa-warning specs-error\'></span></button>'
        for element in ['distro', 'kernel', 'motherboard', 'boot-mode', 'cpu-model', 'cpu-speed', 'arch-use',
                        'arch-supported', 'memory', 'graphics', 'filesystem', 'capacity', 'allocated-space', 'free-space']:
            app.update_page('#spec'+element, 'html', html_tag)

        ## Distro
        try:
            dbg.stdout('Specs', 'Gathering Data: Distribution', 1, 0)
            distro_description = run_external_command(['lsb_release','-d','-s'])
            distro_codename = run_external_command(['lsb_release','-c','-s'])
            app.update_page('#spec-distro', 'html', distro_description)
        except:
            dbg.stdout('Specs', 'Failed to gather data: Distribution', 0, 1)

        ## Kernel
        try:
            dbg.stdout('Specs', 'Gathering Data: Kernel', 1, 0)
            kernel = run_external_command(['uname','-r'])
            app.update_page('#spec-kernel', 'html', kernel)
        except:
            dbg.stdout('Specs', 'Failed to gather data: Kernel', 0, 1)

        ## Motherboard
        try:
            dbg.stdout('Specs', 'Gathering Data: Motherboard', 1, 0)
            motherboard_name = run_external_command(['cat','/sys/devices/virtual/dmi/id/board_name'])
            app.update_page('#spec-motherboard', 'html', motherboard_name)
        except:
            dbg.stdout('Specs', 'Failed to gather data: Motherboard', 0, 1)

        ## CPU Details
        dbg.stdout('Specs', 'Gathering Data: CPU', 1, 0)
        try:
            cpu_model = run_external_command(['lscpu | grep "name"'], True).split(': ')[1]
            app.update_page('#spec-cpu-model', 'html', cpu_model)
        except:
            dbg.stdout('Specs', 'Failed to gather data: CPU Model', 0, 1)

        try:
            try:
                # Try obtaining the maximum speed first.
                cpu_speed = int(run_external_command(['lscpu | grep "max"'], True).split(': ')[1].strip(' ').split('.')[0])
            except:
                # Otherwise, fetch the CPU's MHz.
                cpu_speed = int(run_external_command(['lscpu | grep "CPU MHz"'], True).split(': ')[1].strip(' ').split('.')[0])

            app.update_page('#spec-cpu-speed', 'html', str(cpu_speed) + ' MHz')
        except:
            dbg.stdout('Specs', 'Failed to gather data: CPU Speed', 0, 1)

        try:
            if self.arch == 'i386':
                cpu_arch_used = '32-bit'
            elif self.arch == 'amd64':
                cpu_arch_used = '64-bit'
            else:
                cpu_arch_used = self.arch
            app.update_page('#spec-arch-use', 'html', cpu_arch_used)
        except:
            dbg.stdout('Specs', 'Failed to gather data: CPU Architecture', 0, 1)

        try:
            cpu_arch_supported = run_external_command(['lscpu | grep "mode"'], True).split(': ')[1]
            app.update_page('#spec-arch-supported', 'html', cpu_arch_supported)
        except:
            dbg.stdout('Specs', 'Failed to gather data: CPU Supported Architectures', 0, 1)

        ## Root partition (where Ubuntu MATE is installed) and the rest of that disk.
        try:
            if self.session_type == 'live':
                app.update_page('.spec-hide-live-session', 'hide')
            else:
                dbg.stdout('Specs', 'Gathering Data: Storage', 1, 0)
                ## Gather entire disk data
                root_partition = run_external_command(['mount | grep "on / "'], True).split(' ')[0]
                if root_partition[:-2] == "/dev/sd":            # /dev/sdXY
                    root_dev = root_partition[:-1]
                if root_partition[:-2] == "/dev/hd":            # /dev/hdXY
                    root_dev = root_partition[:-1]
                if root_partition[:-3] == "/dev/mmcblk":        # /dev/mmcblkXpY
                    root_dev = root_partition[:-2]
                else:
                    root_dev = root_partition[:-1]              # Generic
                disk_dev_name = root_dev.split('/')[2]
                dbg.stdout('Specs', 'Ubuntu MATE is installed on disk: ' + root_dev, 1, 4)
                rootfs = os.statvfs('/')
                root_size = rootfs.f_blocks * rootfs.f_frsize
                root_free = rootfs.f_bavail * rootfs.f_frsize
                root_used = root_size - root_free
                entire_disk = run_external_command(['lsblk -b | grep "' + disk_dev_name + '" | grep "disk"'], True)
                entire_disk = int(entire_disk.split()[3])

                ## Perform calculations across units
                capacity_GB =   round(entire_disk/1000/1000/1000,1)
                capacity_GiB =  round(entire_disk/1024/1024/1024,1)
                allocated_GB =  round(root_size/1000/1000/1000,1)
                allocated_GiB = round(root_size/1024/1024/1024,1)
                used_GB =       round(root_used/1000/1000/1000,1)
                used_GiB =      round(root_used/1024/1024/1024,1)
                free_GB =       round(root_free/1000/1000/1000,1)
                free_GiB =      round(root_free/1024/1024/1024,1)
                other_GB =      round((entire_disk-root_size)/1000/1000/1000,1)
                other_GiB =     round((entire_disk-root_size)/1024/1024/1024,1)

                # Show megabytes/mebibytes (in red) if gigabytes are too small.
                if capacity_GB <= 1:
                    capacity_GB = str(round(entire_disk/1000/1000,1)) + ' ' + mb_prefix
                    capacity_GiB = str(round(entire_disk/1024/1024,1)) + ' ' + mib_prefix
                else:
                    capacity_GB = str(capacity_GB) + ' ' + gb_prefix
                    capacity_GiB = str(capacity_GiB) + ' ' + gib_prefix

                if allocated_GB <= 1:
                    allocated_GB =  str(round(root_size/1000/1000,1)) + ' ' + mb_prefix
                    allocated_GiB = str(round(root_size/1024/1024,1)) + ' ' + mib_prefix
                else:
                    allocated_GB = str(allocated_GB) + ' ' + gb_prefix
                    allocated_GiB = str(allocated_GiB) + ' ' + gib_prefix

                if used_GB <= 1:
                    used_GB =  str(round(root_used/1000/1000,1)) + ' ' + mb_prefix
                    used_GiB = str(round(root_used/1024/1024,1)) + ' ' + mib_prefix
                else:
                    used_GB = str(used_GB) + ' ' + gb_prefix
                    used_GiB = str(used_GiB) + ' ' + gib_prefix

                if free_GB <= 1:
                    free_GB =  str(round(root_free/1000/1000,1)) + ' ' + mb_prefix
                    free_GiB = str(round(root_free/1024/1024,1)) + ' ' + mib_prefix
                    app.update_page('#spec-free-space', 'addClass', 'specs-error')
                else:
                    free_GB = str(free_GB) + ' ' + gb_prefix
                    free_GiB = str(free_GiB) + ' ' + gib_prefix

                if other_GB <= 1:
                    other_GB =  str(round((entire_disk-root_size)/1000/1000,1)) + ' ' + mb_prefix
                    other_GiB = str(round((entire_disk-root_size)/1024/1024,1)) + ' ' + mib_prefix
                else:
                    other_GB = str(other_GB) + ' ' + gb_prefix
                    other_GiB = str(other_GiB) + ' ' + gib_prefix

                ## Append data to HTML.
                app.update_page('#spec-filesystem', 'html', root_partition)
                app.update_page('#spec-capacity', 'html', capacity_GB + ' <span class=\'secondary-value\'>(' + capacity_GiB + ')</span>')
                app.update_page('#spec-allocated-space', 'html',  allocated_GB + ' <span class=\'secondary-value\'>(' + allocated_GiB + ')</span>')
                app.update_page('#spec-used-space', 'html', used_GB + ' <span class=\'secondary-value\'>(' + used_GiB + ')</span>')
                app.update_page('#spec-free-space', 'html', free_GB + ' <span class=\'secondary-value\'>(' + free_GiB + ')</span>')
                app.update_page('#spec-other-space', 'html', other_GB + ' <span class=\'secondary-value\'>(' + other_GiB + ')</span>')

                ## Calculate representation across physical disk
                disk_percent_UM_used = int(round(root_used / entire_disk * 100)) * 2
                disk_percent_UM_free = int(round(root_free / entire_disk * 100)) * 2
                disk_percent_other   = (200 - disk_percent_UM_used - disk_percent_UM_free)
                dbg.stdout('Specs', ' Disk: ' + root_dev, 1, 4)
                dbg.stdout('Specs', '  -- OS Used: ' + str(root_used) + ' bytes (' + str(disk_percent_UM_used/2) + '%)', 1, 4)
                dbg.stdout('Specs', '  -- OS Free: ' + str(root_free) + ' bytes (' + str(disk_percent_UM_free/2) + '%)', 1, 4)
                dbg.stdout('Specs', '  -- Other Partitions: ' + str(entire_disk - root_size) + ' bytes (' + str(disk_percent_other/2) + '%)', 1, 4)

                app.update_page('#disk-used', 'width', str(disk_percent_UM_used) + 'px')
                app.update_page('#disk-free', 'width', str(disk_percent_UM_free) + 'px')
                app.update_page('#disk-other', 'width', str(disk_percent_other) + 'px')

        except:
            dbg.stdout('Specs', 'Failed to gather data: Storage', 0, 1)

        ## RAM
        try:
            dbg.stdout('Specs', 'Gathering Data: RAM (Memory)', 1, 0)
            ram_bytes = run_external_command(['free -b | grep "Mem:" '], True)
            ram_bytes = float(ram_bytes.split()[1])
            if round(ram_bytes / 1024 / 1024) < 1024:
                ram_xb = str(round(ram_bytes / 1000 / 1000, 1)) + ' ' + mb_prefix
                ram_xib = str(round(ram_bytes / 1024 / 1024, 1)) + ' ' + mib_prefix
            else:
                ram_xb =  str(round(ram_bytes / 1000 / 1000 / 1000, 1)) + ' ' + gb_prefix
                ram_xib = str(round(ram_bytes / 1024 / 1024 / 1024, 1)) + ' ' + gib_prefix
            ram_string = ram_xb + ' <span class=\'secondary-value\'>(' + ram_xib + ')</span>'
            app.update_page('#spec-memory', 'html', ram_string)
        except:
            dbg.stdout('Specs', 'Failed to gather data: RAM (Memory)', 0, 1)

        ## Graphics
        app.update_page('#spec-graphics', 'html', self.graphics_grep)

        ## Collect missing data differently for some architectures.
        if systemstate.arch == 'powerpc':
            ## Motherboard & Revision
            try:
                dbg.stdout('Specs', 'Gathering Data: PowerPC Motherboard', 1, 0)
                mb_model = run_external_command(['grep','motherboard','/proc/cpuinfo']).split(': ')[1]
                mb_rev = run_external_command(['grep','revision','/proc/cpuinfo']).split(': ')[1]
                app.update_page('#spec-motherboard', 'html', mb_model + ' ' + mb_rev)
            except:
                dbg.stdout('Specs', 'Failed to gather data: PowerPC Motherboard', 0, 1)

            ## CPU and Clock Speed
            try:
                dbg.stdout('Specs', 'Gathering Data: PowerPC CPU', 1, 0)
                cpu_model = run_external_command(['grep','cpu','/proc/cpuinfo']).split(': ')[1]
                cpu_speed = run_external_command(['grep','clock','/proc/cpuinfo']).split(': ')[1]
                app.update_page('#spec-cpu-model', 'html', cpu_model)
                app.update_page('#spec-cpu-speed', 'html', str(cpu_speed))
            except:
                dbg.stdout('Specs', 'Failed to gather data: PowerPC CPU', 0, 1)

            ## Device Name
            try:
                dbg.stdout('Specs', 'Gathering Data: PowerPC Model Name', 1, 0)
                mb_name = run_external_command(['grep','detected','/proc/cpuinfo']).split(': ')[1]
                app.update_page('#spec-motherboard', 'append', ' / ' + mb_name)
            except:
                dbg.stdout('Specs', 'Failed to gather data: PowerPC Model Name', 0, 1)

            ## Boot Mode / PowerMac Generation
            try:
                dbg.stdout('Specs', 'Gathering Data: PowerMac Generation', 1, 0)
                mac_generation = run_external_command(['grep','pmac-generation','/proc/cpuinfo']).split(': ')[1]
                app.update_page('#spec-boot-mode', 'html', 'Yaboot (' + mac_generation + ')')
            except:
                dbg.stdout('Specs', 'Failed to gather data: PowerMac Generation', 0, 1)

        # Check internet connectivity status.
        if self.is_online:
            app.update_page('#specs-has-net', 'show')
            app.update_page('#specs-has-no-net', 'hide')
        else:
            app.update_page('#specs-has-net', 'hide')
            app.update_page('#specs-has-no-net', 'show')

        # Change icon depending on what type of device we are using.
        if self.session_type == 'pi':
            app.update_page('#specs-device-rpi', 'show')
            app.update_page('.specs-hide-pi', 'show')
        elif self.arch == 'powerpc':
            app.update_page('#specs-device-powerpc', 'show')
            app.update_page('.specs-hide-ppc', 'hide')
        elif self.graphics_vendor == 'VirtualBox':
            app.update_page('#specs-device-vbox', 'show')
            app.update_page('.specs-hide-vbox', 'hide')
        elif self.session_type == 'live':
            app.update_page('#specs-live-session', 'show')
            app.update_page('.specs-live-live', 'hide')
        else:
            app.update_page('#specs-device-normal', 'show')

        # Display UEFI/BIOS boot mode.
        if systemstate.arch == 'i386' or systemstate.arch == 'amd64':
            app.update_page('#spec-boot-mode', 'html', self.boot_mode)

        # Hide root storage info if in a live session.
        if self.session_type == 'live':
            app.update_page('.spec-3', 'hide')

        # Data cached, ready to display.
        app.update_page('#specs-loading', 'fadeOut', 'fast')
        app.update_page('#specs-tabs', 'fadeIn', 'fast')
        app.update_page('#specs-basic', 'fadeIn', 'medium')
        app.update_page('#specs-busy-basic', 'fadeOut', 'fast')
        webkit.run_javascript('setCursorNormal()')

    def get_inxi_info(self):
        dbg.stdout('Specs', 'Gathering advanced system information with "inxi"...', 1, 0)
        try:
            inxi_output = str(subprocess.Popen(['inxi','-c','0','-v','5','-p','-d','-xx'], stdout=subprocess.PIPE).communicate()[0])
        except:
            dbg.stdout('Specs', 'Failed to execute collect advanced information. Is "inxi" no longer installed?', 0, 1)

        # Append advanced system information
        try:
            inxi_output = inxi_output.replace("b'","").replace("\\n","\n")
            self.inxi = inxi_output
            app.update_page('#specs-inxi', 'html', '')
            for line in inxi_output.split('\n'):
                app.update_page('#specs-inxi', 'append', line.strip('"').strip("'") + '<br>')
            app.update_page('#specs-inxi-busy', 'slideUp')
            app.update_page('#specs-inxi', 'slideDown')
            app.update_page('#specs-busy-detailed', 'fadeOut', 'fast')
            app.update_page('#specs-inxi-copy', 'slideDown')
            dbg.stdout('Specs', 'Successfully appended advanced system information.', 0, 2)
        except:
            dbg.stdout('Specs', 'Failed to append advanced system information or communicate with "inxi" process.', 0, 1)
            app.update_page('#specs-inxi-busy', 'slideUp')
            app.update_page('#specs-inxi-error', 'slideDown')

    def rpi_resize(self, action, webkit=None):
        if action == 'do-resize':
            subprocess.call(['pkexec', '/usr/lib/ubuntu-mate/ubuntu-mate-welcome-rpi2-partition-resize'])

            def notify(subject, body, icon):
                Notify.init(_('Raspberry Pi Partition Resize'))
                resize_notify=Notify.Notification.new(subject, body, icon)
                resize_notify.show()

            try:
                with open('/tmp/notify_rpi_status') as status_file:
                    status_code = int(status_file.read())
            except:
                status_code = 0

            try:
                with open('/tmp/notify_rpi_text') as misc_file:
                    misc_text = misc_file.read()
            except:
                misc_text = ""

            if status_code == 1:
                notify( _("Root partition has been resized."), _("The filesystem will be enlarged upon the next reboot."), 'dialog-information' )
                self.rpi_resize_pending = True
                app.update_page('#rpi-resized', 'hide')
                app.update_page('#rpi-not-resized', 'hide')
                app.update_page('#rpi-restart-now', 'show')
            elif status_code == 2:
                notify( _("Don't know how to expand."), misc_text + ' ' + _("does not exist or is not a symlink."), 'dialog-error' )
            elif status_code == 3:
                notify( _("Don't know how to expand."), misc_text + ' ' + _("is not an SD card."), 'dialog-error' )
            elif status_code == 4:
                notify( _("Don't know how to expand."), _("Your partition layout is not currently supported by this tool."), 'dialog-error' )
            elif status_code == 5:
                notify( _("Don't know how to expand."), misc_text + ' ' + _("is not the last partition."), 'dialog-error' )
            else:
                notify( _("Failed to run resize script."), _("The returned error code is:") + str(status_code), 'dialog-error' )
                dbg.stdout('Welcome', 'Unrecognised return code for Raspberry Pi resize: ' + str(status_code), 0, 1)

            app.webkit._push_config()

        elif action == 'check':
            if os.path.exists('/.resized'):
                resized = True
            else:
                resized = False

            if resized:
                app.update_page('#rpi-resized', 'show')
                app.update_page('#rpi-not-resized', 'hide')
            else:
                app.update_page('#rpi-resized', 'hide')
                app.update_page('#rpi-not-resized', 'show')

            if self.rpi_resize_pending:
                app.update_page('#rpi-resized', 'hide')
                app.update_page('#rpi-not-resized', 'hide')
                app.update_page('#rpi-restart-now', 'show')

        elif action == 'reboot':
            subprocess.call(['mate-session-save','--shutdown-dialog'])

    def copy_to_clipboard(self, var):
        # Copies text to clipboard, passes 'var' containing what we'd like copying.
        if var == 'inxi':
            contents = self.inxi
        else:
            dbg.stdout('Clipboard', 'Unknown variable to copy: ' + var, 0, 1)
            return

        clipboard = Gtk.Clipboard.get(Gdk.SELECTION_CLIPBOARD)
        clipboard.set_text(contents, -1)
        clipboard.store()
        dbg.stdout('Clipboard', 'Copied contents of: ' + var, 1, 2)

    def get_system_repository_state(self, repo):
        # Used to determine if a system repository is enabled.
        # E.g. "main", "multiverse".
        raw = run_external_command("grep '" + self.codename + " " + repo + "' /etc/apt/sources.list | grep -v 'deb-src' | grep -v 'cdrom'", True)
        # Check for a commented line.
        if raw[:1] != '#':
            dbg.stdout("Repository", "Checked: '" + repo + "' = Enabled", 2, 3)
            return True
        else:
            dbg.stdout("Repository", "Checked: '" + repo + "' = Disabled", 2, 3)
            return False


class Preferences(object):
    def __init__(self):
        self.folder = os.path.join(os.path.expanduser('~'), '.config/ubuntu-mate/welcome')
        self.config = os.path.join(self.folder, 'preferences.json')
        self.data = None
        self.load_prefs()

    def reset_prefs(self):
        if os.path.exists(self.config):
            os.remove(self.config)
        stream = open(self.config, "w")
        stream.write(json.dumps({}))
        stream.close()
        dbg.stdout('Config', 'Preferences reset.', 1, 2)

    def load_prefs(self):
        # Create configuration data if non-existent.
        if not os.path.exists(self.folder):
            dbg.stdout('Config', 'Config folder non-existent. Creating...', 1, 3)
            os.makedirs(self.folder)

        if not os.path.exists(self.config) or os.path.getsize(self.config) < 2:
            dbg.stdout('Config', 'Preferences non-existent. Creating...', 1, 3)
            self.reset_prefs()

        load_error = False
        with open(self.config) as stream:
            try:
                self.data = json.load(stream)
            except Exception as e:
                load_error = True
                dbg.stdout('Config', 'Failed to load preferences. Reason: ' + str(e), 0, 1)

        if load_error:
            dbg.stdout('Config', 'Errors occurred while loading.', 0, 1)
            self.reset_prefs()
        else:
            dbg.stdout('Queue', 'Preferences loaded from file.', 1, 2)

    def write_prefs(self):
        stream = open(self.config, "w+")
        stream.write(json.dumps(self.data))
        stream.close()
        dbg.stdout('Queue', 'Preferences written to file.', 1, 2)

    def set(self, key, data):
        try:
            dbg.stdout('Config', 'Write "' + key + '" => "' + str(data) + '"', 2, 4)
            self.data[key] = data
        except:
            dbg.stdout('Config', 'Failed to write data! "' + key + '" => "' + str(data) + '"', 0, 1)
        self.write_prefs()

    def get(self, key, default):
        try:
            value = self.data[key]
            dbg.stdout('Config', ' Read "' + key + '" => "' + str(value) + '"', 2, 4)
            return value
        except:
            dbg.stdout('Config', ' Read "' + key + '" => "' + str(default) + '" (default)', 2, 4)
            self.set(key, default)
            return default

    def toggle(self, key):
        try:
            value = self.data[key]
            if value == True:
                self.set(key, False)
            else:
                self.set(key, True)
        except:
            self.set(key, True)

    def refresh_pref_page(self, key):
        # Response when setting is changed via "cmd('set-pref?xxx?yyy')" or "cmd('toggle-pref?xxx')"
        try:
            value = self.data[key]
            dbg.stdout('Config', 'Updating preferences page for key: ' + key + ' (' + str(value) + ')', 2, 4)
        except:
            dbg.stdout('Config', 'No data exists for "' + key + '"!', 1, 1)
            return

        # For boolean data, set check boxes
        if type(value) is bool:
            if value == True:
                app.update_page('#pref-' + key, 'removeClass', 'fa-square')
                app.update_page('#pref-' + key, 'addClass', 'fa-check-square')
            else:
                app.update_page('#pref-' + key, 'addClass', 'fa-square')
                app.update_page('#pref-' + key, 'removeClass', 'fa-check-square')


class Arguments(object):
    '''Check arguments passed the application.'''

    def __init__(self):
        self.verbose_enabled = False
        self.simulate_arch = None
        self.simulate_session = None
        self.simulate_codename = None
        self.simulate_no_connection = False
        self.simulate_force_connection = False
        self.jump_software_page = False
        self.locale = None
        self.jump_to = None
        self.font_dpi_override = None

        archs = ['i386', 'amd64', 'armhf', 'arm64', 'powerpc', 'ppc64el']
        sessions = ['guest', 'live', 'pi', 'vbox']

        for arg in sys.argv:
          if arg == '--help' or arg == '-h':
              print('\nUbuntu MATE Welcome Parameters\n  Intended for debugging and testing purposes only!\n')
              print('\nUsage: ubuntu-mate-welcome [arguments]')
              #     | Command                      | Help Text                                     |
              print('  -d, --dev, --debug           Disables locales and is very verbose')
              print('                               intended for development purposes.')
              print('  --font-dpi=NUMBER            Adapt zoom setting based on DPI. Default 96.')
              print('  -h, --help                   Show this help text.')
              print('  --force-arch=ARCH            Simulate a specific architecture.')
              print('                                -- Examples: i386, amd64, armhf, amd64')
              print('  --force-codename=CODENAME    Simulate a specific release.')
              print('                                -- Examples: trusty, wily, xenial')
              print('  --force-net                  Simulate a working internet connection.')
              print('  --force-no-net               Simulate no internet connection.')
              print('  --force-session=TYPE         Simulate a specific type of session.')
              print('                                -- Options: guest, live, pi, vbox')
              print('  --jump-to=PAGE               Open a specific page, excluding *.html')
              print('  --locale=CODE                Locale to use. e.g. fr_FR.')
              print('  --simulate-changes           Simulate software package changes without')
              print('                               modifying the system.')
              print('  -b, -boutique,               Open Welcome only for the software selections.')
              print('  --software-only              ')
              print('  -v, --verbose                Show more details to stdout (for diagnosis).')
              print('')
              exit()

          if arg == '--verbose' or arg == '-v':
              dbg.stdout('Debug', 'Verbose mode enabled.', 0, 0)
              dbg.verbose_level = 1

          if arg.startswith('--force-arch'):
              try:
                  self.simulate_arch = arg.split('--force-arch=')[1]
                  if self.simulate_arch not in archs:
                      dbg.stdout('Debug', 'Unrecognised architecture: ' + self.simulate_arch, 0, 1)
                      exit()
                  else:
                      dbg.stdout('Debug', 'Simulating architecture: ' + self.simulate_arch, 0, 0)
              except:
                  dbg.stdout('Debug', 'Invalid arguments for "--force-arch"', 0, 1)
                  dbg.stdout('Debug', 'Available Options: ' + str(archs), 0, 1)
                  exit()

          if arg.startswith('--force-session'):
              try:
                  self.simulate_session = arg.split('--force-session=')[1]
                  if self.simulate_session not in sessions:
                      dbg.stdout('Debug', 'Unrecognised session type: ' + self.simulate_session, 0, 1)
                      exit()
                  else:
                      dbg.stdout('Debug', 'Simulating session: ' + self.simulate_session, 0, 0)
              except:
                  dbg.stdout('Debug', 'Invalid arguments for "--force-session"', 0, 1)
                  dbg.stdout('Debug', 'Available Options: ' + str(sessions), 0, 1)
                  exit()

          if arg.startswith('--force-codename'):
              self.simulate_codename = arg.split('--force-codename=')[1]
              dbg.stdout('Debug', 'Simulating Ubuntu release: ' + self.simulate_codename, 0, 0)

          if arg == '--force-no-net':
              dbg.stdout('Debug', 'Simulating the application without an internet connection.', 0, 0)
              self.simulate_no_connection = True

          if arg == '--force-net':
              dbg.stdout('Debug', 'Forcing the application to think we\'re connected with an internet connection.', 0, 0)
              self.simulate_force_connection = True

          if arg == '--software-only' or arg == '--boutique' or arg == '-b':
                dbg.stdout('Welcome', 'Software Boutique is no longer part of Welcome.', 0, 3)
                if os.path.exists("/usr/bin/software-boutique"):
                    dbg.stdout('Welcome', "In future, launch with 'software-boutique' instead.", 0, 0)
                    os.execv("/usr/bin/software-boutique", [""])
                else:
                    dbg.stdout('Welcome', 'Software Boutique not found. It may not be installed.', 0, 1)
                    exit(1)

          if arg == '--dev' or arg == '--debug' or arg == '-d':
              dbg.stdout('Debug', 'Running in debugging mode.', 0, 0)
              dbg.verbose_level = 2
              self.locale = 'null'

          if arg.startswith('--locale='):
              self.locale = arg.split('--locale=')[1]
              dbg.stdout('Debug', 'Setting locale to: ' + self.locale, 0, 0)

          if arg.startswith('--jump-to='):
              self.jump_to = arg.split('--jump-to=')[1]
              dbg.stdout('Debug', 'Opening page: ' + self.jump_to + '.html', 0, 0)

          if arg.startswith('--font-dpi='):
              try:
                  self.font_dpi_override = int(arg.split('--font-dpi=')[1])
              except:
                  dbg.stdout('Debug', 'Invalid Override Font DPI specified. Ignoring.', 0, 1)
                  return
              dbg.stdout('Debug', 'Overriding font DPI to ' + str(self.font_dpi_override) + '.', 0, 0)

    def override_arch(self):
        if not self.simulate_arch == None:
            systemstate.arch = self.simulate_arch

    def override_session(self):
        if not self.simulate_session == None:
            if self.simulate_session == 'vbox':
                systemstate.graphics_vendor = 'VirtualBox'
                systemstate.graphics_grep = 'VirtualBox'
            else:
                systemstate.session_type = self.simulate_session

    def override_codename(self):
        if not self.simulate_codename == None:
            systemstate.codename = self.simulate_codename


##################################
#  Program Initialisation
##################################
if __name__ == "__main__":

    # Process any parameters passed to the program.
    dbg = Debug()
    arg = Arguments()

    # Application Initialisation
    setproctitle.setproctitle('ubuntu-mate-welcome')
    data_path = whereami()

    # Set up translations and strings
    trans = Translations(data_path)

    # Welcome Features
    pref = Preferences()
    systemstate = SystemState()
    app = WelcomeApp()

    # Argument Overrides
    arg.override_arch()
    arg.override_session()
    arg.override_codename()

    dbg.stdout('Welcome', 'Application Ready.', 0, 0)
    app.run()
