data/* usr/share/ubuntu-mate-welcome/
hicolor/* usr/share/icons/hicolor/
mate-settings-welcome.menu etc/xdg/menus/
org.ubuntu-mate.welcome.policy usr/share/polkit-1/actions/
ubuntu-mate-welcome usr/bin/
ubuntu-mate-welcome.1 usr/share/man/man1
ubuntu-mate-welcome-repository-installer usr/lib/ubuntu-mate/
ubuntu-mate-welcome.desktop etc/skel/.config/autostart/
ubuntu-mate-welcome.desktop usr/share/applications/
update-mate-menu-welcome /usr/sbin/

