name: ubuntu-mate-welcome
adopt-info: ubuntu-mate-welcome
summary: Welcome screen for Ubuntu MATE
description: |
 A welcome screen for Ubuntu MATE that provides links to helpful
 resources, utilities and a selection of software packages.

base: core20
grade: stable
confinement: classic

parts:
  ubuntu-mate-welcome:
    plugin: nil
    build-packages:
      - gettext
      - git
      - python3
      - python3-polib
    override-pull: |
      snapcraftctl pull
      cd $SNAPCRAFT_PROJECT_DIR
      VER=$(grep __VERSION__ ubuntu-mate-welcome | head -n 1 | cut -d'=' -f2 | sed 's/ //g' | sed "s/'//g")
      REV=$(git rev-parse --short HEAD)
      snapcraftctl set-version $VER-$REV
    override-build: |
      snapcraftctl build
      cd $SNAPCRAFT_PROJECT_DIR
      ./welcome-po.py --update-pos
      ./welcome-po.py --install
      ./edgar-allan translate-all
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/ubuntu-mate-welcome/
      cp -a data/* $SNAPCRAFT_PART_INSTALL/usr/share/ubuntu-mate-welcome/

      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/
      cp -a hicolor/* $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/

      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/locale
      cp -a locale/* $SNAPCRAFT_PART_INSTALL/usr/share/locale/

      # Modify the icon paths for the snap.
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications/
      sed 's|Icon=software-boutique|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/software-boutique\.svg|' ubuntu-mate-software.desktop > $SNAPCRAFT_PART_INSTALL/usr/share/applications/ubuntu-mate-software.desktop
      sed 's|Icon=ubuntu-mate|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/ubuntu-mate\.svg|' ubuntu-mate-welcome.desktop > $SNAPCRAFT_PART_INSTALL/usr/share/applications/ubuntu-mate-welcome.desktop

      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      cp ubuntu-mate-welcome $SNAPCRAFT_PART_INSTALL/usr/bin/

      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/ubuntu-mate/
      cp ubuntu-mate-welcome-repository-installer $SNAPCRAFT_PART_INSTALL/usr/lib/ubuntu-mate/

      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/man/man1
      cp ubuntu-mate-welcome.1 $SNAPCRAFT_PART_INSTALL/usr/share/man/man1

    prime:
      - usr/bin/
      - usr/share/ubuntu-mate-welcome/
      - usr/share/icons/hicolor/*/apps/software-boutique.png
      - usr/share/icons/hicolor/*/apps/ubuntu-mate.png
      - usr/share/icons/hicolor/*/apps/software-boutique.svg
      - usr/share/icons/hicolor/*/apps/ubuntu-mate.svg
      - usr/share/locale/
      - usr/share/applications/
      - usr/lib/ubuntu-mate/
      - usr/share/man/man1/ubuntu-mate-welcome.1

  wrapper:
    after:
      - ubuntu-mate-welcome
    plugin: dump
    source: files/

apps:
  ubuntu-mate-welcome:
    command: bin/wrapper $SNAP/usr/bin/ubuntu-mate-welcome
    desktop: usr/share/applications/ubuntu-mate-welcome.desktop
    environment:
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
      LIBGL_ALWAYS_SOFTWARE: 1
  software-boutique:
    command: bin/wrapper $SNAP/usr/bin/ubuntu-mate-welcome --boutique
    desktop: usr/share/applications/ubuntu-mate-software.desktop
    environment:
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
      LIBGL_ALWAYS_SOFTWARE: 1
