#!/bin/sh

# Only attempt to write the files when not running in the live session
if [ ! -f /usr/share/glib-2.0/schemas/40_ubuntu-mate-live.gschema.override ]; then

  cat << AUTOSTART > /etc/xdg/autostart/ubuntu-mate-welcome-autostart.desktop
[Desktop Entry]
Version=1.0
Name=Welcome
Comment=Ubuntu MATE Welcome autostart
Categories=
Terminal=false
Type=Application
Exec=/snap/bin/ubuntu-mate-welcome --autostart
OnlyShowIn=MATE;
StartupNotify=false
NoDisplay=true
AUTOSTART

  cat << POLICY > /usr/share/polkit-1/actions/org.ubuntu-mate.welcome.policy
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">
<policyconfig>
  <vendor>ubuntu-mate</vendor>
  <vendor_url>http://hal.freedesktop.org/docs/PolicyKit/</vendor_url>

  <action id="org.ubuntu-mate.welcome">
    <description>Ubuntu MATE Welcome Repository Installer</description>
    <message>Helper utility for the Ubuntu MATE Welcome screen that can enable software repositories.</message>
    <icon_name>system-run</icon_name>
    <defaults>
      <allow_any>no</allow_any>
      <allow_inactive>no</allow_inactive>
      <allow_active>yes</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">$SNAP/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer</annotate>
  </action>
</policyconfig>
POLICY

  cat << MENU > /etc/xdg/menus/mate-settings-welcome.menu
<!DOCTYPE Menu PUBLIC '-//freedesktop//DTD Menu 1.0//EN' 'http://standards.freedesktop.org/menu-spec/menu-1.0.dtd'>
<Menu>
    <Name>Desktop</Name>
    <Include>
            <Filename>$SNAP/ubuntu-mate-welcome.desktop</Filename>
    </Include>
    <Layout>
        <Merge type="menus"/>
        <Separator/>
        <Filename>$SNAP/ubuntu-mate-welcome.desktop</Filename>
        <Merge type="files"/>
    </Layout>
</Menu>
MENU

fi