#!/bin/sh

#$SNAP/usr/sbin/update-mate-menu-welcome
#update-icon-caches /usr/share/icons/hicolor
#update-desktop-database

cat << AUTOSTART > /etc/xdg/autostart/ubuntu-mate-welcome.desktop
[Desktop Entry]
Version=1.0
Name=Welcome
Comment=Ubuntu MATE Welcome autostart
Categories=
Terminal=false
Type=Application
Exec=$SNAP/usr/bin/ubuntu-mate-welcome --autostart
OnlyShowIn=MATE;
StartupNotify=false
NoDisplay=true
AUTOSTART

cat << POLICY > /usr/share/polkit-1/actions/org.ubuntu-mate.welcome.policy
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">
<policyconfig>
  <vendor>ubuntu-mate</vendor>
  <vendor_url>http://hal.freedesktop.org/docs/PolicyKit/</vendor_url>

  <action id="org.ubuntu-mate.welcome">
    <description>Ubuntu MATE Welcome Repository Installer</description>
    <message>Helper utility for the Ubuntu MATE Welcome screen that can enable software repositories.</message>
    <icon_name>system-run</icon_name>
    <defaults>
      <allow_any>no</allow_any>
      <allow_inactive>no</allow_inactive>
      <allow_active>yes</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">$SNAP/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer</annotate>
  </action>
  <action id="org.ubuntu-mate.rpi2partresize">
    <description>Ubuntu MATE Welcome Partition Resizer for the Raspberry Pi 2</description>
    <message>Helper utility for the Ubuntu MATE Welcome screen that can resize the partitions for the Raspberry Pi 2.</message>
    <icon_name>system-run</icon_name>
    <defaults>
      <allow_any>no</allow_any>
      <allow_inactive>no</allow_inactive>
      <allow_active>yes</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">$SNAP/usr/lib/ubuntu-mate/ubuntu-mate-welcome-rpi2-partition-resize</annotate>
  </action>
</policyconfig>
POLICY