#!/bin/sh

# Only attempt to write the files when not running in the live session
if [ ! -f /usr/share/glib-2.0/schemas/40_ubuntu-mate-live.gschema.override ]; then

  cat << AUTOSTART > /etc/xdg/autostart/ubuntu-mate-welcome-autostart.desktop
[Desktop Entry]
Version=1.0
Name=Welcome
Name[da]=Velkommen
Name[sl]=Welcome
Name[hu_HU]=Üdvözöljük
Name[ko_KR]=환영합니다
Name[it]=Benvenuto
Name[ro]=Bine ați venit
Name[cs]=Vítejte
Name[hy]=Բարի Գալուստ
Name[nb]=Velkommen
Name[et]=Tere tulemast
Name[lt_LT]=Sveiki
Name[el]=Καλώς ήλθατε
Name[sr]=Добродошлица
Name[sr@latin]=Dobrodošli
Name[sv]=Välkommen
Name[ja]=ようこそ
Name[be_BY]=Вітаем
Name[ar]=مرحباً
Name[pt]=Boas-vindas
Name[nb_NO]=Velkommen
Name[es]=Bienvenido
Name[nl]=Welkom
Name[fr_CA]=Bienvenue
Name[pl]=Welcome
Name[oc]=Benvengut
Name[sk]=Vitajte
Name[zh_CN]=欢迎
Name[de]=Willkommen
Name[zh_TW]=歡迎
Name[es_ES]=Bienvenido
Name[is]=Velkomin(n)
Name[fr_FR]=Bienvenue
Name[bg]=Добре Дошли
Name[en_GB]=Welcome
Name[pt_BR]=Bem-vindo
Name[nl_NL]=Welkom
Name[tr_TR]=Hoş Geldiniz
Name[eu]=Ongi etorri
Name[es_419]=Bienvenido
Name[fi_FI]=Tervetuloa
Name[id]=Selamat Datang
Name[ru]=Добро пожаловать
Name[ms_MY]=Aluan
Name[he]=ברוך הבא
Name[ca_ES]=Benvinguda
Categories=
Terminal=false
Type=Application
Exec=/snap/bin/ubuntu-mate-welcome --autostart
OnlyShowIn=MATE;
StartupNotify=false
NoDisplay=true
AUTOSTART

  cat << POLICY > /usr/share/polkit-1/actions/org.ubuntu-mate.welcome.policy
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">
<policyconfig>
  <vendor>ubuntu-mate</vendor>
  <vendor_url>http://hal.freedesktop.org/docs/PolicyKit/</vendor_url>

  <action id="org.ubuntu-mate.welcome">
    <description>Ubuntu MATE Welcome Repository Installer</description>
    <message>Helper utility for the Ubuntu MATE Welcome screen that can enable software repositories.</message>
    <icon_name>system-run</icon_name>
    <defaults>
      <allow_any>no</allow_any>
      <allow_inactive>no</allow_inactive>
      <allow_active>yes</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">$SNAP/usr/lib/ubuntu-mate/ubuntu-mate-welcome-repository-installer</annotate>
  </action>
</policyconfig>
POLICY

  cat << MENU > /etc/xdg/menus/mate-settings-welcome.menu
<!DOCTYPE Menu PUBLIC '-//freedesktop//DTD Menu 1.0//EN' 'http://standards.freedesktop.org/menu-spec/menu-1.0.dtd'>
<Menu>
    <Name>Desktop</Name>
    <Include>
            <Filename>$SNAP/ubuntu-mate-welcome.desktop</Filename>
    </Include>
    <Layout>
        <Merge type="menus"/>
        <Separator/>
        <Filename>$SNAP/ubuntu-mate-welcome.desktop</Filename>
        <Merge type="files"/>
    </Layout>
</Menu>
MENU

fi